# DE WAARDEN VOLGENS DE WET


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*De mens is een moreel wezen omdat hij goed en kwaad kan onderscheiden. Het goede kennen wij door onze schepping in het beeld en naar de gelijkenis van God, hoewel wij door de zonde de verbinding met God verloren hebben. Wij weten nog wel van God, maar kennen Hem niet persoonlijk. Het geweten herinnert ons aan wat werkelijk goed is, wat waarde heeft, ook door bewuste of onbewuste gevoelens van schaamte en schuld. Het blijkt dat we het goede kennen, maar niet weten hoe we goede mensen moeten zijn. Zelfs als we goede dingen doen, zijn we nog geen goede mensen. De Here Jezus waarschuwt ons dat een goede boom geen slechte vruchten kan dragen, maar dat een slechte boom geen goede vruchten voortbrengt (Mattheüs 7.18).*
*De wet is het eerste woord van God waardoor Hij ons aanspreekt als dienaren die zijn wil behoren te doen en ons oordeelt in onze zonden.*

## De wet openbaart de wil van God

We herinneren ons dat het kwaad geen deel van de goede schepping is, maar dat het de schepping binnengedrongen is als de leugen, dat de mens gelijk kan zijn aan God. Deze leugen is de erfzonde, die ons scheidt van onze Schepper. Gescheiden van Hem leven we een zinloos leven, in duisternis en verdwaald in ons eigen kwaad en het kwaad van deze wereld.  Echter, het evangelie van de Here Jezus Christus nodigt ons uit in Hem te geloven, in Zijn dood en opstanding, en in het geloof verlossing te ontvangen. Een verlossing, die bestaat uit vergeving van de zonde, bevrijding van haar overmacht op ons leven door het herstel van onze relatie met God. 

Wij ontvangen deze verlossing in de vorm van een belofte die we geloven en die zal worden vervuld bij het herstel van alle dingen. Tijdens ons leven ervaren we de dubbele werkelijkheid van heiligheid en van zonde. De Heilige Geest, die in ons werkt door het geloof in de Here Jezus, helpt ons een heilig leven te leiden, bevrijd van de macht van de zonde, waardoor onze motieven veranderen, zelfs als we regelmatig in gebreke blijven. Hij leert ons in alle omstandigheden van het leven te vragen: Here, wat wilt u dat ik doe? Het antwoord dat we krijgen is dat de Here wil dat we ons bekeren, Christus navolgen en Zijn heilige wet gehoorzamen (Mattheüs 4.17; Markus 10.17ss.; Johannes 8.12). 

## De wet bevestigt de waarden

In het geestelijke leven is de wet Gods eerste antwoord op onze zonde. Door de wet confronteert Hij ons met onze morele werkelijkheid, met onze onvolmaaktheid en met ons kwaad. Na onze bekering, dat is nadat wij nieuw leven te hebben ontvangen door geloof in de Here Jezus, laat dezelfde wet ons zien hoe we moeten leven. Ze leert ons wijsheid, wat inhoudt dat we leren ons te laten leiden door de vreze des Heren (Psalm 19.7; Spreuken 1.7).

In feite doet de wet niet anders dan bevestigen wat we al door ons geweten wisten. Ze bevestigt de waarden die met de schepping gegeven zijn, de vitale waarden, de sociale waarden, de grote en de pure waarden. Wie weet niet dat je niet iemand van het leven kunt beroven, dat je niet kunt stelen of liegen zonder je schuldig te voelen? Wie geeft toe aan seksuele onreinheid zonder schaamte? Wie voelt zich niet schuldig als hij zijn ouders oneer aandoet? Als we goed doen, juist als we er geen voordeel bij hebben, voelen we ons goed, maar als we iets verkeerds doen, voelen we ons ongemakkelijk, zelfs wanneer we nog niet de gevolgen van ons kwaad hebben ondervonden.  Het kan zijn dat we in onze verharding onze schuldgevoelens verdringen, maar dan nog voelen we schaamte. En als we ook de schaamte verdringen, bekruipen ons de gevoelens van onlust en zinloosheid, verbittering en cynisme, depressie en levensangst. De Bijbelse profetie waarschuwt ons: de goddelozen hebben geen vrede (Jes.48.22; 57.21).

## Gods wet is nauwkeuriger dan het geweten

De apostel Paulus zegt in Rom.2.14: Wanneer de heidenen, die de wet niet hebben, van nature toch doen wat de wet gebiedt, dan zijn dezen, ofschoon zonder wet, zichzelf tot wet.  Dit intuïtieve weten van goed en kwaad is het natuurrecht of de natuurwet. Het blijkt dat Gods geopenbaarde wet de waarden bevestigt die we door het geweten kennen. Echter, de geopenbaarde wet is in verschillende opzichten nauwkeuriger en dwingender. Allereerst al omdat ze wordt verkondigd in de naam van God. Omdat de Here God is, kunnen we geen andere goden hebben, kunnen we de schepselen of afbeeldingen van schepselen niet als goden aanbidden, moeten we Zijn heilige Naam eren en rust betrachten om daaraan vorm te geven. En vervolgens de geboden die we in het voorbijgaan al hebben samengevat: geen moord plegen en geen overspel, niet stelen en geen geen vals getuigenis afleggen in de rechtbank tegen een ander. Zelfs mogen we het kwade begeren niet in overweging nemen. Ook deze geboden gelden omdat God God is. Hij heeft ze als waarden in de schepping gelegd en bevestigt ze door de geopenbaarde wet. Ze herinneren ons aan Gods heiligheid. 

## De morele wet
Gewoonlijk onderscheiden we drie soorten wetten in de Bijbel, de morele, de ceremoniële en de burgerlijke, hoewel de Bijbel zelf dit onderscheid niet maakt. De morele wetten zijn de altijd geldende wetten, die de met de schepping gegeven waarden en instellingen bevestigen en beschermen. Als later het Nieuwe Testament zegt dat de gelovigen vrij zijn van de wet, dan betekent dat nooit dat we vrij zijn om te doen en te laten wat we willen, dat de waarden en instellingen niet meer gelden, maar dat wij vrij zijn van de veroordeling door de wet vanwege onze zonde. Dat we niet afgerekend zullen worden op onze gehoorzaamheid, omdat Christus de wet heeft vervuld voor ons. Haar geldende straffen heeft Hij gedragen en aan haar positieve eisen heeft Hij voldaan en wij worden uitgenodigd en aangemoedigd door de Heilige Geest Zijn voorbeeld te volgen (Rom. 7.6; Gal. 3.13; 1Cor. 11.1).

## De ceremoniële en de burgerlijke wet

Terwijl de morele wet universele geldigheid heeft, hebben de ceremoniële wetten slechts tijdelijke betekenis. Ze golden slechts vanaf Mozes en waren al in het Oude Testament aan verandering onderhevig  (Gal. 3.17). In de psalmen en de profeten komen we teksten tegen die de offerdienst relativeren en opnieuw oriënteren (Psalm 51.16,17; Jesaja 1.10-15; 53; Jeremía 7.21-28). Wat betreft hun praktijk, we weten niet hoe de feesten en de offers de tijd van de ballingschap doorstonden. Wel dat het Nieuwe Testament begint met de priesterzoon Johannes de Doper, die niet offert, maar optreedt met een nieuwe rite, zijn bekeringsdoop (Mattheüs 3). Vervolgens wijst hij Jezus aan als het Lam van God dat de zonde der wereld wegneemt  (Johannes 1.29). De Hebreeënbrief legt omstandig uit dat Zijn dood het enige, ware en altijdgeldende offer is. Het blijkt dat het offer in het christendom zelfs een diepere betekenis kreeg dan het in het Jodendom ooit gehad had. Het Nieuwe Testament geeft ook aan de Oudtestamentische feesten nieuwe betekenis en voert nieuwe rites en tradities in: de doop en het Heilig Avondmaal. Al deze momenten tonen aan hoe dynamisch de ceremoniële praktijk in de Bijbel is.   

De burgerlijke wetten van het Oude Testament zijn de praktische weerslag van de morele wetten. Ze hebben hun oorsprong in een patriarchale, tribale en rurale samenleving en evolueerden met de historische ontwikkeling van het volk mee. Vooral toen Israël een koninkrijk werd en Jeruzalem hoofdstad, moesten de wetten wetten geactualiseerd worden. De onderwerping van Israël aan de wereldrijken en de diaspora in de nadagen van het Oude Testament dwongen opnieuw tot allerlei aanpassingen, welke in de Joodse traditie in de Talmoed bewaard zijn. 
	
## De 7 Noachitische geboden

De Joodse traditie verdedigt de universele geldigheid van de morele wetten door middel van de zogenaamde Zeven Noachitische Geboden, die teruggaan op het middeleeuwse Jodendom in Moorse rijk van Córdoba. Het zijn deze: 

1. Rechtvaardige wetgeving en rechtspraak  (vergelijk het 9e gebod).
2. Verbod de Schepper of in Zijn naam iets van het geschapene te vervloeken (vergelijk het 3e gebod).
3. Verbod op afgoderij  (1ste en 2e gebod). 
4. Verbod op moord  (6e gebod)
5. Verbod van onzedelijkheid en incest  (vergelijk 7e gebod).
6. Verbod op diefstal en mensenroof  (8e gebod).
7. Verbod op het eten van levend vlees (verbod op eten van bloed in Oude Testament en Hand.15.20,29; 21.25). 

## Slot 

Elke mens heeft een moreel bewustzijn, we weten intuïtief van goed en kwaad, we kennen de waarden en weten wat geen waarde heeft. Echter, dit bewustzijn is zwak, onzeker en machteloos, zodat we het goede wel kennen, maar niet weten hoe het te doen. We vrezen wel het kwaad, maar hebben niet de macht en vaak niet eens de wil het te vermijden. Om een goed mens te zijn, moet de Here ons vernieuwen door het geloof in de Here Jezus, en ons door de Heilige Geest een nieuwe gehoorzaamheid leren. Dit proces wordt in de Bijbel genoemd, met Christus sterven om ook met Hem op te staan in een nieuw leven (Rom.6; H.C. 17.45). De betekenis van de morele wet in het geestelijke leven is eerst pedagogisch, zij overtuigt van zonde, en later didactisch door een rein en zuiver leven te onderwijzen aan de gelovigen.  

De wet in het Oude Testament is deel van het verbond van God met Israël. Zijn eerste woord. Het na-Bijbelse Jodendom begreep dat de ceremoniële en civiele wetten tijdelijke en nationale betekenis hadden, maar  bevestigde de universele betekenis van de morele wet.

## Oefeningen
1. Wat is de functie van het geweten.
2. Leg uit welke betekenis de wet heeft voor de waarden.
3. Waarom is niemand onbekend met de wet?
4. Op welke wijze staat de geopenbaarde wet boven het natuurrecht?
5. Welke soorten wet onderscheiden we in de Bijbel?
6. Wat is de geldigheid van de morele wet?
7. Wat is de geldigheid van de ceremoniële en burgerlijke wet?
8. Welke relevantie hebben de Noachitische geboden voor ons?



