# DE DECALOOG {#sec-wijsheid}


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*De mens is een moreel wezen, maar ons moreel besef is zwak en onzeker. We kennen het kwaad, maar niet op zo’n manier dat we het grondig haten en verwerpen; we kennen het goede, maar niet genoeg om het werkelijk lief te hebben. Om echt lief te hebben wat goed is, moet de Here ons vernieuwen en dat doet Hij door het geloof in de Here Jezus. Het geloof reinigt ons hart, dat wil zeggen, onze motieven (Handelingen 15.9). De Heilige Geest leert ons een nieuwe gehoorzaamheid aan Gods heilige Wet. Dezelfde wet die ons in het begin veroordeelde vanwege onze zonden, wordt nu een leefregel. En hoewel we haar niet volledig kunnen vervullen vanwege de macht van de zonde in ons leven, bevestigen we wat Psalm 119.97 zegt, dat we haar liefhebben.*

## De tien woorden

In de Joodse traditie heten de vijf boeken van Mozes Thora, wet, onderwijzing, richtlijn. Dit betekent dat niet alleen de geboden en verboden (morele, ceremoniële en civiele) wet zijn in de Bijbelse zin van het woord, maar ook de Oudtestamentische verhalen en geschiedenissen. In werkelijkheid is het zo dat alle Bijbelse vertellingen een verplichtend karakter hebben, omdat ze de waarheid God en van de mens onderwijzen. Samen met de geboden en verboden vormen ze het organische geheel van de Thora, de wet van Mozes, geactualiseerd door de profetische en poëtische literatuur en door de wijsheid van het Oude Testament. Gecanoniseerd in de Tenach, vormen de drie delen van de Joodse canon - Thora, de Profeten en de Geschriften - de constitutionele geschiedenis van Israël1.

Heel de Oudtestamentische wet, in feite heel de Israëlitische ethiek, wordt samengevat door en geconcentreerd in de Wet van de Tien Geboden, die in de Joodse traditie ook Thora heet. Twee keer vinden we haar afgedrukt in het Oude Testament, in Ex.20.1-17 en Deut. 5.6-22. Het volk Israël ontving haar door een theofanie (manifestatie van God) op de berg Horeb, een gebeurtenis die een diepe indruk maakte en waardoor Israël voor altijd wist dat de Wet van de Here was (Ex.13.9). De Decaloog proclameert de Naam van Here als de God en Verlosser van Zijn volk en definieert tegelijkertijd de fundamentele morele waarden van het leven. 

De Tien Woorden van het Verbond (Ex.34.28; Deut. 4.13) hebben in verschillende christelijke tradities verschillende vorm gekregen. Katholieken en lutheranen combineren het verbod op afgoderij en het vereren van afbeeldingen (het eerste en het tweede gebod), maar verdelen het gebod tegen hebzucht (het tiende) in tweeën. De kerkvaders scheidden het verbod op afgoderij in twee delen, het eerste richtte zich tegen de afgoderij zelf en het tweede tegen het vereren van beelden en afbeeldingen. Om praktische redenen zullen we deze gewoonte volgen, omdat ze de meest gangbare is in de gereformeerde en evangelische traditie. Echter we erkennen dat de Joodse traditie zeker te verdedigen is. De rabbijnen lazen de preambule als het eerste gebod en combineerden vervolgens de verboden van afgoderij en afbeeldingen als tweede gebod. De preambule van het Ik ben de Here uw God, die u uit het land Egypte, uit het diensthuis, heeft geleid, is inderdaad de grondwettelijke formule van het verbond, en daardoor het belangrijkste woord van heel de wet (zie Lev.26.12) . De overige geboden, die we kort zullen bespreken volgens de tekst van Ex.20.1-17, zijn er van afgeleid. 

## De eerste drie geboden

Het eerste en tweede gebod vormen een eenheid met verschillende accenten. Het eerste eist exclusieve dienst aan de Here, terwijl het tweede de afgodische vormen van de eredienst uitsluit. Het woord voor Mijn aangezicht van het eerst gebod, wordt ook vertaald met vanwege Mijn / in Mijn aanwezigheid, of Mij tot last. De aanbidding van andere – valse - goden is een ondraaglijke last voor de ware God. Het tweede gebod is geen radicaal verbod op kunst, maar het leert dat geen enkel menselijk werk ooit onze kennis of beeld van God kan bepalen. Het derde gebod vervolgt het tweede. Het verbod op afbeeldingen van God betekent ook dat wij ons moeten richten naar het Woord dat Zijn Naam openbaart. Tegelijkertijd moeten we de integriteit van deze Naam bewaren en nooit oppervlakkig over Hem spreken. Al onze verwijzingen naar God, hetzij in de prediking, de gebeden, de lofprijzing, de overdenking of het publieke getuigenis, moeten waardig en eerbiedig zijn. 

## Het vierde gebod

Het vierde gebod combineert morele, ceremoniële en burgerlijke elementen. Het morele en het burgerlijke is het recht op rust, dat praktisch geregeld moet worden. Het ceremoniële aspect is het heiligen van deze rust met de dubbele motivatie in de beide versies van de Decaloog door de voltooide schepping en door de uittocht (Ex.20.11; Deut.5.15). Misschien zelfs dat het werkwoord gedenken (imperatief) verwijst naar een sabbatsbewustzijn of sabbatscultuur die ouder is dan de Decaloog. In de christelijke traditie heeft het vierde gebod er nog een motief bijgekregen, toen het gebruikelijk werd de opstanding van Christus te vieren op de eerste dag van de week, die in de vierde eeuw n.C. week aangewezen werd als rustdag. Het blijkt dus dat het oorspronkelijke scheppingsmotief voor de rustdag wordt bevestigd en versterkt in de heilsgeschiedenis, eerst door de éxodus en later nogmaals door de opstanding van Christus. De verschuiving van de rustdag van de laatste naar de eerste dag van de week is moreel en burgerlijk van geen betekenis, omdat ze het wekelijkse ritme van één rustdag handhaaft. Ceremonieel is ze legitiem omdat ze ons toestaat de opstanding van Christus te vieren als het begin van een nieuwe schepping, waarbij wij ons beide eerdere motieven van de rustdag, de schepping en de exodus, blijven herinneren. Het evenwicht tussen het morele en het ceremoniële aspect van de rustdag maakt het mogelijk werkelijk te rusten. Wie dit evenwicht niet kent, zal niet echt tot rust komen. Jezus zelf, als Heer van de sabbat, waarschuwt ons ervoor het ceremoniële aspect van de sabbat niet uit te spelen tegen het morele (Mattheüs 12.8).

Niet iedere gelovige begrijpt en gehoorzaamt het vierde gebod aangaande de sabbat op dezelfde wijze, maar duidelijk is dat het dat het een combinatie is van het recht – het heilzame gebod – om elke week één dag niet te werken, met de opdracht deze rust te heiligen. We mogen één dag van de week reserveren voor de overdenking, de aanbidding en de dankzegging van Gods Naam. Het gebod bevestigt met grote nadruk dat ieder zijn ondergeschikten deze rustdag behoort te gunnen. Zelfs de gedomesticeerde dieren hebben recht op rust. Op deze wijze bevestigt het vierde gebod de hoge waarde van rust en beperkt het alle vormen van dienstbaarheid tot maximaal zes dagen in de week, waardoor het ook de slavernij ondermijnt. De bijzondere wetten aangaande het sabbats- en het jubeljaar, die afgeleid zijn van het sabbatsgebod, voorkomen enerzijds duurzame verarming en anderzijds grootgrondbezit. Zelfs onderkennen ze de uitputting van de vruchtbare grond. 
	
## Het vijfde tot en met het tiende gebod

Het vijfde gebod is geen gebod voor minderjarigen (hoewel Paulus het wel zo leest in Efeziërs 6:1-4), maar eerder een opdracht aan kinderen, in de kracht van het leven, om voor hun bejaarde ouders te zorgen. Vooral ook omdat zij door deze ouders het verbond met God hebben ontvangen. De volgende geboden bevestigen, net als het vijfde gebod, de scheppingsorde en de fundamentele waarden van het leven: de waardigheid en het recht op het leven, de onaantastbaarheid van het huwelijk en van erfgoed en eigendom. De wet beschermt in de eerste plaats de rechten van degenen die zichzelf niet kunnen verdedigen. Geen machtig heer zal zich iets toe-eigenen van wat van een ander is, niet het leven van een ondergeschikte, niet zijn eigendom, niet zijn vrouw (zie 2Sam.12.1-14). Het negende gebod beschermt de armen en de zwakken tegen leugens en omkoping in het gericht (zie 1R.12). 

De wet eindigt met een bijzondere waarschuwing van hoog moreel en geestelijk niveau: we moeten ons niet alleen onthouden van daden die schade veroorzaken, maar ook van alle overweging ervan. Het tiende gebod is een waarschuwing tegen gierigheid, hebzucht en wellust, want gierigheid is de wortel van alle kwaad. Eveneens een waarschuwing tegen het verzamelen van schatten op de aarde, en tegen het nakijken van een vrouw om haar te begeren (zie Genesis 3.6; 4.19; 6.2; Mattheüs 5.28; 6.19; 1Tim.6.10). In plaats van te begeren van wat onze naaste toebehoort, of we het voor ons zelf missen of zelfs dat ook niet, moeten we hem in zijn bezit respecteren, hem het beste wensen en zijn belangen verdedigen. Dit weer volgens de gouden regel: wat je wilt dat mensen jou doen, doe dat hen ook (Mt 7.12). 

## Slot
De Wet van de Tien Geboden is een morele code die de hoge waarden van het leven afkondigt als normen. We moeten ons deze waarden eigen maken, zodat ze deel van ons leven worden als motieven en deugden. De Here Jezus heeft de wet samengevat voor alle tijden in het krachtige dubbele gebod de Here, onze God, lief te hebben met heel ons hart, en met heel onze ziel, en met heel ons verstand en onze naaste lief te hebben als onszelf (Matteüs 22:37-39). 

## Oefeningen
1. Herhaal de dubbele betekenis van de wet voor het geestelijke leven.
    
2. Lees de tekst van de wet in Ex.20 en Deut. 5. Wat is het verschil?

3. Waarom moeten we de Joodse traditie de preambule als eerste gebod te lezen ernstig overwegen?

4. Wat is het verband tussen het eerste en het tweede gebod?

5. Wat is het verband tussen het tweede en het derde gebod?

6. Wijs het morele, burgerlijke en ceremoniële motief aan in het sabbatsgebod.

7. Wijs de drie lagen in de christelijke zondagsviering aan.

8. Is de verplaatsing van de rustdag van de sabbat naar de zondag legitiem, in morele, burgerlijke en ceremoniële zin?

9. Welke waarden worden bevestigd en verdedigd in de eerste vier geboden?

10. Welke waarden worden verdedigd in het 5e tot het 9e gebod, en welke ondeugden aangewezen?

11. Waarom zijn deze geboden zowel moreel als burgerlijk?

12. Wat is het karakter van het 10e gebod, moreel, ceremonieel of burgerlijk?

13. Welke waarden worden verdedigd in het 10e gebod en welke ondeugden worden aangewezen?

