# DE VRIJHEID VAN DE WET EN  DE WET VAN DE VRIJHEID


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



Waarden zijn kwaliteiten en principes die altijd verdedigd moeten worden. Ze zijn inherent aan de schepping, evenwel geopenbaard, bevestigd, gespecificeerd en gepreciseerd door de Bijbel en daardoor beter bekend als de Bijbelse waarden, dan als natuurlijke. De wet van het Oude Testament, geconcentreerd in de Tien Geboden, is de belangrijkste bron van de waarden die in de Bijbel worden onderwezen, maar niet de enige. Ook het evangelie van Jezus Christus en de wijsheidsliteratuur van het Oude en Nieuwe Testament bevestigen dezelfde waarden.

## De wet markeert een geestelijke en morele ruimte

De wet bevestigt en onthult niet alleen waarden, maar markeert ook een ruimte om in overeenstemming met deze waarden te leven. In Lev. 18.4 wordt gezegd: U zult mijn verordeningen volbrengen en mijn inzettingen in acht nemen en daarin wandelen. De wet is om daarin te wandelen. Ze is een geestelijke en en morele ruimte, bepaald door de rechten en inzettingen van God als grens en horizon. Leven in deze ruimte is wijsheid (Deut. 4.6; Rom. 10.5). In Ef. 2.10 heet het vervullen van de wet wandelen in goede werken.

De wet van de Tien Geboden is de concentratie en de essentie van het geheel van regels, aansporingen, geboden, inzettingen en raadgevingen die het leven van het volk van God regelen. Gehoorzaamheid aan deze wet brengt geen verzoening van de zonde in absolute zin, maar beschermt wel tegen een ongeordend en ongebreideld leven in zonde en ongerechtigheid. De wet beschermt ons tegen erger. Het Oude Testament vraagt gehoorzaamheid aan de wet van het volk dat bevrijd is uit Egypte; in het Nieuwe Testament is de wet de leefregel van een volk dat Jezus Christus navolgt in geloof, hoop en liefde, gehoorzaam aan Zijn opdracht niet meer te zondigen (Johannes 5.14; 8.11). Leven volgens de wet is het protocol van het leven van de discipelen van de Here Jezus. De buitenkant van het geloof, de verklaring van goed gedrag, die op zichzelf niet verdienstelijk is, maar wel onmisbaar. Door gehoorzaamheid aan de wet verkrijgen we niets wat we niet al lang hebben door het geloof, maar ongehoorzaamheid aan de wet betekent een bestaan ​​zoeken buiten het heil van Jezus Christus. Ongehoorzaamheid aan de wet bevestigt en handhaaft de zonde, met het vreselijke gevolg van het niet-vinden van het heil.

## De paradox van de wet

Gods wet speelt een paradoxale rol in ons leven. Haar doel is ons te beschermen tegen het kwaad en ons te redden van zijn macht. Echter, vanwege onze tekortkomingen en zonden klaagt ze ons aan en veroordeelt ze ons. De geboden die ons het goede wijzen, worden tot een vonnis. Bijvoorbeeld, het gebod om niet te stelen is eerst een aanbeveling tot een goed en eerlijk leven, maar als wij die aanbeveling naast ons neer leggen, is het een veroordeling van alle vormen van diefstal. Op dezelfde manier ook de andere geboden. De wet rechtvaardigt het goede en veroordeelt het kwade, met gevolg dat niemand van ons kan zeggen vrij te zijn van veroordeling, omdat hij alleen maar goed heeft gedaan. Echter, op het moment dat we ons bekeren en erkennen dat we Gods veroordeling waard zijn, komt het evangelie tussenbeide door ons verzoening en vergeving te beloven. Het eerste woord van God is inderdaad de wet, maar het tweede dat de veroordeling door de wet buiten werking zet, is het evangelie. In het evangelie is er geen veroordeling voor hen die in Christus Jezus zijn, en dat ondanks onze tekortkomingen (Rom.8.1).

## Legalistisch begrip van de Thora

Het is vooral de apostel Paulus die in het Nieuwe Testament strijdt tegen een legalistisch en ceremonieel begrip van de wet, waardoor de Joden van zijn tijd het genadekarakter van het verbond vergeten hadden (zie Galaten 3.17,19,21,23). Beter dan wie dan ook begreep Paulus dat de wet haar ware doel, namelijk verlossing, niet kan bewerkstelligen, en dat alleen de genade van God die werkzaam is in het geloof, deze kracht heeft. Gerechtigheid, zoals Paulus haar begrijpt, is geen strikte gehoorzaamheid aan de wet, zeker niet aan de ceremoniële wet, maar is een genade die God schenkt, door Jezus Christus (Rom.3.20, 28; Gal.2.16; 3.10). Gerechtigheid bij Paulus is rechtvaardiging en daarom strijdt hij tegen de suggestie dat de wet een reddend vermogen heeft. Hij benadrukt het feit dat zij later, dat is na de verbondsbeloften, vanwege de ongehoorzaamheid van het volk, aan het verbond is toegevoegd, juist ook om het verbond tegen deze ongehoorzaamheid te beschermen (Gal. 3.19; 1Tim.1.9). Zodoende is er door de wet kennis van zonde (Rom.3.20; 5.13; 7.7). Bovendien, allen, die het van werken der wet verwachten, liggen onder de vloek; want er staat geschreven: Vervloekt is ieder, die zich niet houdt aan alles, wat geschreven is in het boek der wet, om dat te doen (Gal.3.10). De ervaring van Paulus is dat het gebod dat ten leven moest leiden, voor hem juist ten dode bleek te zijn. Zelfs is het zo dat de wet de zonde activeert, want toen het gebod kwam, herleefde de zonde (Rom. 7.8-13; 5.20).

## Wet en evangelie

Het evangelie bevestigt en onderwijst dezelfde waarden als de Wet, dezelfde morele principes en kwaliteiten die inherent zijn aan de schepping en die we intuïtief kennen door ons geweten. Evenwel, terwijl de wet ons veroordeelt vanwege onze zonde, belooft het evangelie ons vergeving en verzoening vanwege het offer van Christus.

Het evangelie is in de eerste plaats de profetische boodschap die gepredikt werd door Johannes de Doper, van bekeert u want het Koninkrijk van de hemel is nabij. Deze boodschap werd door Jezus en de apostelen overgenomen als het evangelie van het Koninkrijk van God en de Naam van Jezus (Matteüs 4:23; 10:7; Handelingen 8:12). Het hele Nieuwe Testament is de ontplooiing van deze boodschap. Door zijn oproep tot bekering bevestigt het evangelie de wet en haar inherente waarden, zoals gerechtigheid, liefde, betrouwbaarheid etc. Tegelijk is het evangelie een belofte van vergeving en verzoening door Jezus Christus, die het Lam Gods is dat de zonde der wereld wegneemt (Matteüs 9:6; Marcus 2:10; Johannes 1.27, 34). Door zich te onderwerpen aan alle eisen door de wet, heeft Christus haar vervuld. Na deze bevrijding van de veroordeling door de wet opent zich een nieuwe ruimte waarin wij Christus gehoorzamen, door het voorbeeld dat Hij gaf door Zijn dood en opstanding na te volgen.

## De vervulling van de wet

De vervulling van de wet is ook het einde van de wet (Mat.5.17; Rom. 10.4). Er zijn verschillende elkaar aanvullende verklaringen van deze gedachte:

-   Het blijkt dat de wet haar eigen vervulling voorbereidde door de komst te verwachten van degene die de macht zou hebben haar ware bedoeling te openbaren (Gal. 3:24-25). \_ Jezus vervulde de wet door Zijn volkomen gehoorzaamheid voor zichzelf en Zijn volk en daardoor verloor de wet haar functie. Ze kon niet langer eisen, wat Christus reeds volbracht had (Gal. 5:23).
-   Christus vervulde de wet door zichzelf aan haar veroordeling te onderwerpen. Hij is door de wet aan de wet gestorven (Gal. 2:19). Op het moment van het sterven van iemand die de wet overtreden heeft, – of van iemand die zijn plaats inneemt – wordt de wet vervuld. In Christus – vertegenwoordigd door Christus - zijn de gelovigen gestorven aan de wet. Dit wil zeggen dat we niet meer veroordeeld kunnen worden door de wet omdat zij haar gezag over ons heeft verloren (Rom.8.1; Gal.2.19).
-   Christus maakte een einde aan de wet door de zonde van de wereld weg te nemen. Waar geen overtreding mogelijk is, heeft de wet haar functie verloren (zie Rom. 4.15).
-   Door het bloed van Christus is er vergeving van zonden. Ook vergeving van de zonde doet de wet haar functie verliezen.

Als we deze gedachten combineren, kunnen we zeggen dat Christus, door zich te allen tijde en in alle gevallen die de wet kan voorzien aan de eisen van de wet te hebben onderworpen, haar vloek en haar eis nietig verklaard heeft en volmaakte gerechtigheid voor de gelovigen verworven heeft. Door dit alles heeft Hij de wet vervuld en is Hij het einde van de wet (Rom.10.4), zodat het volk, dat Hij vertegenwoordigt, vrij is van de wet (Rom. 7.2,3,6; 8.2)

## De wet van de vrijheid

In de paulinische brieven is navolging van Christus het hoogste pedagogische principe: wees navolgers van mij; zoals ik navolger van Christus ben (1Co.11.1; zie 1Cor.4.16; Ef.5.1; Fil.3.17; 1Thess.1.6; 2.14; Hebr. 6.12). In de praktijk van het leven betekent navolging van Christus en van de apostelen zelfverloochening, afzien van persoonlijk voordeel en toewijding aan Christus en Zijn Koninkrijk. De navolging van Christus is volgens de wet van de vrijheid. Terwijl Paulus de nadruk legt op de vrijheid van de wet, de bevrijding van de veroordeling door de wet omdat Christus haar vervuld heeft, wijst Jakobus op de wet van vrijheid. Het is de verplichting die de gelovigen voelen, de wens die we hebben om de heilige wet van God te vervullen, vrijwillig op grond van onze eigen motieven, vanwege de liefde tot God en de diepe dankbaarheid jegens Hem (Jakobus 1.25; 2.8-13; zie Johannes 14.15,21; 15.10; 1Johannes 2.3-5).

## Oefeningen

1.  Leg uit de betekenis van het werkwoord wandelen in Lev. 18.4 en Ef. 2.10.
2.  Leg uit dat de wet het protocol is voor het leven van het volk van God.
3.  Wat is het paradoxale van de wet?
4.  Wat is een legalistisch begrip van de Thora?
5.  Welke betekenis geeft Paulus aan gerechtigheid?
6.  Welke inhoud heeft het evangelie van het Koninkrijk?
7.  Welke verschillende betekenissen heeft het vervullen van de wet’
8.  Leg uit dat Christus het einde van de wet is.
9.  Leg uit dat wet en evangelie dezelfde waarden bevestigen, maar verschillen in hun pedagogiek.
10. Wat is de vrijheid van de wet en wat is de wet der vrijheid?
