# DE WAARDEN VOLGENS HET EVANGELIE


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*De geopenbaarde wet van God onthult, bevestigt en preciseert de waarden die met de schepping gegeven zijn en die we herkennen in het geweten. Het evangelie bevestigt dezelfde waarden en deugden als de wet, echter met dit verschil, dat de wet ons veroordeelt vanwege onze zonde, maar dat het evangelie ons vergeving belooft vanwege het offer van Christus. Christus heeft voor ons de vloek van de wet ontkracht, haar eisen vervuld en volmaakte gerechtigheid voor Zijn volk verworven.  Tegelijk met ons te bevrijden van het oordeel van de wet, verandert Hij ook haar karakter door haar voor ons te transformeren in de wet van de vrijheid. De wet van de vrijheid bevestigt dezelfde waarden als de oorspronkelijke wet, maar we hoeven haar niet langer te vrezen als een vijandige macht die ons veroordeelt en straft. Integendeel wij hebben haar lief omdat we weten dat ze er voor ons bestwil is. We willen haar vrijwillig gehoorzamen om God te eren en om goed te doen aan onze naasten, en we betreuren elk moment waarop we haar niet hebben gerespecteerd en zullen respecteren.*

## Het evangelie van Jezus Christus 

Het evangelie van Jezus Christus sloot aan bij de profetische boodschap van Johannes de Doper: het bekeert u, want het Koninkrijk der hemelen is nabij. Jezus en de apostelen bogen de boodschap van Johannes om tot het evangelie van het Koninkrijk van God en de Naam van Jezus (Mattheüs 4:23; 10.7; Handelingen 8.12). Het hele Nieuwe Testament is de ontplooiing van dit evangelie, waarvan we de ethische relevante in drie woorden kunnen samenvatten: bekering, vergeving en navolging. 

-Bekering;  Altijd is bekering de uitnodiging van Gods kant het leven nogmaals en opnieuw te beginnen. In het Oude Testament is ze in de eerste plaats het opgeven en afzweren van de afgoden en terugkeer tot de God van de vaderen en tot Zijn verbond. In het Nieuwe Testament is ze het verzaken van de zonden en de vernieuwing van het leven en het denken door een nieuwe relatie met God, door het geloof in Jezus Christus waardoor de vruchten van de Geest voortgebracht kunnen worden (Mattheüs 3.8; Lukas 3.8; Rom.12.2; Gal.5.22). 

-Vergeving van zonde; De oudtestamentische beloften van vergeving van zonden en verzoening met God worden krachtig vervuld in het evangelie (Ex.34.7; Num.14.18; Lev. 4.26; 2Kr.7.14; Psalm 86.5; Jer. 31.34; 50.20; Jona 4.2; Micha.7.18; Rom. 5 10; 2C.5.19,20). Jezus Christus, de Zoon van God, die macht had zonden te vergeven, is het Lam van God dat de zonde van de wereld wegneemt (Mattheüs 9:6; Markus 2:10; Johannes 1:29, 36; Hebreeënbrief). 

-Navolging van Christus; Christenen zijn discipelen van de Here Jezus en hun levensstijl wordt bepaald door Zijn voorbeeld  (Handelingen 9.1). De navolging van Christus is de navolging van Zijn kruis en Zijn opstanding: Als iemand achter Hem aan wil komen, laat hij dan zichzelf verloochenen, zijn kruis opnemen en Hem volgen. Want ieder die zijn leven zal willen behouden, zal het verliezen, maar ieder die zijn leven verliest omwille van Christus, zal het vinden. Want wat zal het een mens baten als hij de hele wereld wint en zijn eigen ziel verliest? Of wat zal een mens voor zijn ziel geven? (Mattheüs 16:24-26; zie Mattheüs 10:10:38; Lukas 14:27). 
In de theologie van Paulus is de navolging van Christus een belangrijk pedagogisch principe. De apostel spoort de gelovigen aan: wees mijn navolgers, zoals ik ook Christus navolg (1Co.11.1; zie 1Cor.4.16; Ef.5.1; Fil.3.17; 1Thes.1.6; 2.14; Hebr. 6.12). In de praktijk van het leven betekent de navolging van Christus en de apostelen zelfverloochening, afzien van eigenbelang en toewijding van het hele leven, van de wil, het verstand, de gevoelens, het lichaam en zelfs de hartstochten aan Christus en Zijn kerk.

## De Bergrede

Het evangelie als boodschap van bekering, vergeving van zonde en navolging van Christus wordt in geconcentreerde vorm aangetroffen in de Bergrede, de eerste van de vijf toespraken van Jezus die structuur geven aan het evangelie van Mattheüs (Mattheüs 5-7). De Bergrede is één van de indrukwekkendste teksten ooit geschreven. De inhoud en de stijl bepalen haar buitengewone autoriteit. Ze is een krachtige boodschap die door de zaligsprekingen van Mattheüs 5.1-12 de menigten van mensen die Jezus navolgen aanspreekt als discipelen, en hen vervolgens een vernieuwde ethiek geeft door toewijding aan haar waarden en deugden aan te bevelen. Deze nieuwe ethiek is de hogere gerechtigheid waarover de Here Jezus spreekt in Mattheüs 5.20 en 48 en die Hij oplegt aan Zijn discipelen in de vorm van het gebod van dubbele liefde uit Mattheüs 22:37-40: de Here, onze God, lief te hebben met heel ons hart en met heel onze ziel en met geheel  ons verstand (Mattheüs 22.37). 

Mat. 5.1 zegt nadrukkelijk dat Jezus, toen Hij de berg opging, de menigte zag, waarnam, in het oog nam. Het zijn dezelfde menigten als die van Matt. 4.23, toen Hij hun het Evangelie van het Koninkrijk predikte en hun ziekten en aandoeningen genas. In Mat. 9.36 zijn de condities van deze menigte het motief van Zijn diepe medelijden, omdat Hij ze ziet als schapen zonder herder, waardeloos, hulpeloos en verstrooid. Later is hetzelfde mededogen de reden voor de vermenigvuldiging van de broden (Matt. 14:14-15; 15:32). 

Als Jezus de berg bestijgt om Zijn rede te houden, komen Zijn discipelen naar Hem toe. Ze maken deel uit van dezelfde sociale klasse als de menigten, en tegelijkertijd zijn ze de voorhoede van Jezus’ geestelijke Koninkrijk. De scharen moeten worden wat de discipelen al zijn: discipelen. Hoewel Jezus Zijn discipelen aanspreekt, is het duidelijk dat hij door hen heen de menigte toespreekt. In het laatste vers van de Bergrede blijkt het dat Mattheüs geen belangstelling heeft voor het effect van de rede op de discipelen, maar wel voor de reactie van het volk, dat zich verwondert over Jezus’ leer (Mattheüs 7.28,29). 

## Belofte of verplichting

Een belangrijke vraag bij de Bergrede is of ze in essentie evangelie (belofte) of moraal (wet) is. En als ze in wezen belofte (evangelie) is, hoe belangrijk zijn dan haar morele aansporingen? Zijn het slechts pedagogische uitdagingen om het hart van de zondaren te breken door een scherpe interpretatie van de wet en hen zodoende open te stellen voor het evangelie? Andersom, als de Bergrede in wezen wet is, welke plaats neemt ze dan in het evangelie in? Deze vragen stellen opnieuw één van de kernvragen van de christelijke theologie aan de orde, die van de verhouding van wet en evangelie, een vraag die bepalend is voor de ethiek. 

Wet en evangelie hebben een verschillende bediening, maar ze bevestigen dezelfde waarden. De wet eist en veroordeelt, het evangelie belooft en vergeeft. In werkelijkheid vullen wet en evangelie elkaar aan, omdat beide hetzelfde doel hebben: een nieuwe relatie met God, een relatie van liefde en gehoorzaamheid. De wet is machteloos zonder het evangelie en het evangelie is zonder betekenis als er geen wet is. Waar de belofte van vergeving van zonden wordt gepredikt, wordt ook de vraag van gehoorzaamheid aan God aan de orde gesteld. Waar gehoorzaamheid wordt gepredikt, moet ook over vergeving worden gesproken 
Het Evangelie van het Koninkrijk

Wij verdedigen de gedachte dat de wet en het evangelie in de Bergrede een nieuwe eenheid vormen. De rede is een integraal onderdeel van het Mattheüsevangelie, een uitwerking van de boodschap van Jezus, die dezelfde was als die van Johannes de Doper en later van de discipelen: bekeert u, want het Koninkrijk der hemelen is nabij. Deze boodschap is het Evangelie van het Koninkrijk, naar zijn vorm een blijde boodschap, naar zijn inhoud een belofte van het Koninkrijk, naar zijn essentie een profetische proclamatie die onderwerping aan dit Koninkrijk en zijn hoge gerechtigheid eist (Mattheüs 4.23; 9.35; 10.7;  6.33; 5.20). Een dynamische boodschap die als kracht van God zelf de verandering (bekering) bewerkstelligt die zij eist en afdwingt (Rom. 1.16). Een boodschap die geloof wekt in haar zegeningen en beloften, die onderwerping aan haar gezag bewerkstelligt en die door dit alles een nieuwe ethiek ontwerpt, die zich onderscheidt door honger en dorst naar gerechtigheid, het dubbele verlangen om rechtvaardig te zijn en gerechtigheid te doen (Matt. 5.6) en een evangelische aansporing tot volmaaktheid is (Mattheüs 5.48).  

## Oefeningen
   
1. Met welke drie begrippen kunnen we de ethische implicatie van het evangelie samenvatten?

2. Welke  betekenissen heeft bekering?

3. Wat is de pedagogiek van de Bergrede; m.a.w., hoe worden de scharen aangesproken?

4. Op welke wijze komt de kwestie van wet en evangelie in de Bergrede aan de orde?

5. Leg uit dat de Bergrede beide is: a) het evangelie van het Koninkrijk en b) de ethiek van het Koninkrijk.