# DE VOLMAAKTHEID VAN DE DISCIPELEN  

*Waarden zijn morele kwaliteiten en principes die we altijd moeten verdedigen. Ze maken deel uit van de schepping van de mens, worden onthuld en bevestigd door de wet van God, door het evangelie van Jezus Christus en door de wijsheid, die van de Heilige Geest is. Het evangelie is de boodschap van Johannes de Doper, herhaald door Jezus en de apostelen, van «Bekeert u, want het Koninkrijk der hemelen is nabij». Een boodschap die komst van het Koninkrijk van God aankondigt, met al zijn geestelijke, morele en praktische weldaden, als vergeving van zonde en eeuwig leven. Een boodschap die vraagt ​​om bekering en geloof en die vorm krijgen in de navolging van Christus. Het evangelie concentreert zich in de Bergrede, de eerste van de vijf redes van Jezus die de structuur van het evangelie van Mattheüs bepalen (Matteüs 5-7).*

## De bERGREDE

De Bergrede is de samenvatting en concentratie van het evangelie van het Koninkrijk dat Jezus onderwijst (Matteüs 4:23). De belofte van het Koninkrijk is onvoorwaardelijk; zij sluit iedere hoorder in en niemand wordt uitgesloten. In de eerste plaats geldt ze de menigte van verarmde en geestelijk verwaarloosde mensen van Jezus’ tijd en van alle tijden: de armen van geest, mensen die hongeren en dorsten naar gerechtigheid en die vervolgd worden om wille van de gerechtigheid (Matt. 5.3,10; 9.36). Vervolgens geldt ze iedereen die door de woorden van Jezus zijn geestelijke armoede, zijn honger en dorst naar gerechtigheid ervaart en aanvaardt. Op deze wijze onderwijst de Bergrede een vernieuwde ethiek die de Bijbelse waarden opnieuw en scherper formuleert en die van de discipelen een hogere toewijding vraagt. Een ethiek die de volmaaktheid van God tot voorbeeld heeft en haar climax vindt in de liefde voor de vijand (Matteüs 5.44).

## Volmaaktheid als belofte

De  volmaaktheid die de Bergrede belooft en tegelijk vraagt is deel van de verlossing die door het Evangelie geschonken wordt. Hoewel ze onmisbaar is om het Koninkrijk der hemelen binnen te gaan, is ze geen voorwaarde (Matteüs 5.20). De morele aansporingen tot volmaaktheid zijn evangelische instructies, onderdeel van dezelfde kracht van God die de menigte van mensen die de wet niet kent tot discipelen van de Here maakt (Johannes 7.49). Ze zijn geen wet die eist en veroordeelt, noch een moreel systeem dat gedrag eist en verwerpt, maar eerder uitnodigingen om het voorbeeld van de Meester te volgen. Het aanvaarden van deze uitnodiging is het doen van de woorden van Jezus. Het niet doen van Zijn woorden betekent het weigeren en opgeven van het discipelschap. Wie naar de woorden van Jezus luistert en ze doet, is een wijs mens; wie niet luistert en ze niet doet, is een dwaas die zijn huis bouwt op het zand (Matteüs 7:24-29).

## Een geestelijke uitdaging
De volmaaktheid die Jezus leert in de Bergrede is niet moreel, maar geestelijk, naar Zijn eigen voorbeeld. Ze is niet kwantitatief, maar kwalitatief; niet het aantal goede daden telt, maar de motivatie achter alle daden. De volmaaktheid van de discipelen is vrijwillig, volgens de wet van de vrijheid, want Jezus gebruikt geen enkele vorm van externe discipline (Jakobus 1.25). Ze is meer een uitdaging dan een werkelijkheid; ze krijgt vorm in de bekering waardoor de discipelen levenslang belijden en ervaren dat ze de ware volmaaktheid niet op eigen kracht kunnen bereiken.  

De Bergrede ontkent niet de geldigheid van de morele wetten en minacht ze ook niet. Integendeel, de getrouwe en praktische vervulling van de morele wet, uitgelegd als een navolging van Christus en volgens de wil van zijn Vader, heeft geestelijke waarde (Matt. 5.17-20). De discipelen zijn niet alleen het zout en het licht van de wereld vanwege de gerechtigheid die zij ontvangen, maar ook vanwege de gerechtigheid die zij beoefenen (Matt. 7:20). Daardoor laten zij zien dat zij kinderen van de Vader zijn (Matt. 5:16).

## Een praktische uitdaging
	
Het blijkt dat de volmaaktheid van de discipelen geestelijk is, maar niet utopisch, bovenmenselijk of extremistisch. Door haar diepe menselijkheid is zij een positieve uitdaging die overeenkomt met de hoogste en diepste behoeften en noden van de individuele mensen en van de samenleving, in de geschiedenis en van alle culturen. Discipelen hoeven geen supermensen of zelfs engelen te zijn, maar discipelen, mensen die leren van hun Meester, die hen onderwijst aangaande hun persoonlijke en publieke relaties, de zuiverheid van het huwelijk en het geweten. Jezus spreekt met de discipelen over eedzwering en wraakoefening, over het oordelen en beoordelen van anderen, hoe ze behoren te offeren, te bidden en te vasten, te leven in het vertrouwen op God, te midden van de dagelijkse beslommeringen (Mattheüs 5.21-7.11).

De waarden zoals de Bergrede ze onderwijst zijn de elementen van een nieuwe levensstijl en van praktische uitdagingen, die met optimisme en realisme moeten worden aanvaard in moeilijke situaties en complexe structuren. Ze moedigen ons aan tot navolging van Christus, van Hem te leren als discipelen. Daarbij geldt de belofte dat waar het Evangelie van het Koninkrijk een terugkeer naar God bewerkstelligt, het ook leidt tot morele vernieuwing. 

## Oefeningen
1. Definieer nogmaals de waarden.

2. Definieer het evangelie.

3. Op welke wijze is het Evangelie van het Koninkrijk een onvoorwaardelijke belofte?

4. Wie worden als eersten aangesproken door het Evangelie van het Koninkrijk?

5. Hoe gelden de zaligsprekingen ook mensen die niet maatschappelijk of economisch arm zijn, politiek machteloos en rechteloos?

6. Verklaar dat de volmaaktheid van de discipelen geen voorwaarde is om het Koninkrijk van God binnen te gaan en toch noodzakelijk.

7. Verklaar de relatie tussen de volmaaktheid en de navolging.

8. Verklaar dat de volmaaktheid niet moreel is maar geestelijk, niet kwantitatief, maar kwalitatief. Meer uitdaging dan werkelijkheid.

9. Verklaar dat de volmaaktheid vorm krijgt in de bekering.

10. Wat is de geestelijke waarde van de morele en praktische handhaving van de ethiek van de Bergrede?

11. Verklaar dat de volmaaktheid van de discipelen een positieve uitdaging is.

12. Wat zijn de thema's die Jezus onderwijst in de Bergrede?

13. Verklaar de relatie tussen geestelijke en morele vernieuwing.

## Oefeningen bij het schema

14. Verklaar de spanning tussen enerzijds het geestelijke gezag van de Bergrede, dat absoluut is, en anderzijds haar relatieve morele en praktische gezag.

15. Verklaar het geestelijke gezag van de diverse delen van de Bergrede.

16. Verklaar het paradoxale/contrasterende gezag van de diverse delen van de Bergrede.

17. Verklaar het illustratieve, educatieve gezag van de diverse delen van de Bergrede.

18. Wat is de gouden regel en waar vinden we haar in de Bergrede?


