# DE ETHIEK VAN HET KONINKRIJK 

*In de voorgaande hoofdstukken van Waarden en Verantwoordelijkheid hebben we de ethiek van het Koninkrijk, gelezen als deel van het evangelie van Koninkrijk en samengevat gevonden in de Bergrede van Matteüs 5-7. We stelden een geestelijk en tegelijkertijd realistisch begrip van deze ethiek voor: haar te verstaan als genade – een kracht van God tot behoud; volmaaktheid als belofte - en tegelijk als een praktische handleiding voor en een uitdaging tot een goed en zuiver leven. Een krachtige evangelische aansporing tot volmaaktheid.* 

## De waardering van de Bergrede in de theologie 

In de katholieke traditie werd het belang van de ethiek van het Koninkrijk beperkt tot de geestelijkheid en het kloosterleven. Alleen gelovigen die voor het celibaat en voor het klooster kozen, zouden de hoge gerechtigheid waarvan Jezus spreekt in Mattheüs 5.20 kunnen vervullen, door middel van de drie belangrijke geloftes: armoede, kuisheid en gehoorzaamheid. Dit ascetische begrip van de ethiek van het Koninkrijk leidt tot twee soorten christenen, geestelijken en leken, beide groepen met een verschillend moreel niveau. 

Het historische protestantisme twijfelt eveneens aan de praktische toepassing van de Bergrede in het dagelijks leven en wel vanwege zijn pessimistisch begrip van de heiliging. Vanwege zijn even pessimistische ecclesiologie (kerkleer) twijfelt het ook aan de mogelijkheid de waarden van de Bergrede in praktijk te brengen in de christelijke gemeente. Het verwacht dat de ethiek van de Bergrede pas aan het einde van de tijden, met het herstel van alle dingen, tot volledige ontplooiing zal komen. Het gevolg van dit scepticisme is een zekere morele onverschilligheid, met zelfs de rechtvaardiging van onrechtvaardige en onderdrukkende structuren. Als machtskerk met een imperiale theologie legitimeerde het protestantisme veelal de autocratische en onderdrukkende machtsstructuren, aanvalsoorlogen, uitbuiting van arbeiders, kolonialisme en slavernij. Kerkelijke kritiek op deze structuren was eeuwenlang een uitzondering. 
	
De afwachtende houding van het historische protestantisme ten opzichte van de Bergrede wordt gedeeltelijk gecorrigeerd door de gedachte dat de rede een intensivering is van de morele wet, die schuldig spreekt en veroordeelt in naam van de hogere gerechtigheid, om het bewustzijn van zonde te verdiepen. Volgens dit pedagogische begrip van de rede, onderwijst Jezus geen praktische ethiek, maar eerder een volmaaktheid die niemand kan bereiken. Door de Bergrede zou Hij de oproep tot bekering en geloof in Hemzelf als de personificatie van hogere gerechtigheid bekrachtigen. 

## Het radicale begrip van de Bergrede
	
Er zijn andere, meer optimistische stromingen, die wel een praktisch begrip van de Bergrede verdedigen, in de zin van persoonlijke volmaaktheid en morele en vervolgens ook praktische verbetering van de wereld. Voorbeelden van dit praktische begrip van de Bergrede zijn:

- Het radicaal en utopisch christendom (anabaptisme, mennonisme, quakers, tolstoïsme, social-gospel, bevrijdingstheologie) heeft door de eeuwen heen een theologie van de armen verdedigd, pacifistisch en anti-gouvernementeel, met kritiek op de machtige en rijke staats- en volkskerken. De radicalen begrepen de Bergrede als een politiek en sociaal programma en zagen de kerk als een Gideonsbende om het Koninkrijk in de geschiedenis, als heilige gemeenschap, te verwezenlijken. Vrijwel alle vormen van radicalisme hebben vroeger of later hun principes gecorrumpeerd en verloochend, en hun aanhangers teleurgesteld. 

-De liberale theologie van de XIX eeuw baseerde op de Bergrede haar moralistische begrip van het christendom. Zij leerde dat het Koninkrijk der Hemelen bestaat uit de geleidelijke en progressieve verwezenlijking van vrede en gerechtigheid in deze wereld. Ieder die meewerkt deze vrede en gerechtigheid tot stand te brengen, of hij nu christenen of ongelovig is, is burger van het Koninkrijk. Echter, in de liberale theologie worden de beloften volledig geabsorbeerd door de wet, het evangelie door de ethiek. Ze brengt zo mogelijk alle delen van de Schrift in harmonie met dit moralisme en elimineert wat niet in harmonie gebracht kan worden. 

- Radicalisme en liberalisme gaan veelal in elkaar over, zoals aan het begin van de XXI eeuw ook weer blijkt in het christelijke ecologisme, met zijn groene evangelie en groene catechismus.

## De evangelicalen en hun begrip van de Bergrede
	
Een derde trend, de meest voorkomende in het huidige mondiale protestantisme, combineert elementen van de geestelijke interpretatie van het klassieke protestantisme met elementen van het radicale christendom. De evangelischen erkennen dat het Koninkrijk der Hemelen een eschatologische werkelijkheid is en dat de waarden van het Koninkrijk geestelijk zijn, maar zij willen ook de morele en praktische betekenis die de Bergrede ongetwijfeld heeft, gestand doen. Voor de evangelischen is de ethiek van de Bergrede een tussentijdse ethiek, een geheel van morele voorschriften die als leidraad dienen voor de tijd tussen het de opstanding van Christus en het eschaton (einde der tijden). De ethiek van de Bergrede heeft daarbij geen algemene geldigheid, want zij geldt slechts de discipelen van Christus. Het is het ethische programma voor de kerk, zoals Jezus haar wilde, een contrastgemeenschap. 

De evangelische interpretatie van de Bergrede is de meest evenwichtige maar heeft toch twee bezwaren: (1) door de Bergrede als een uitzonderlijke ethiek te begrijpen scheidt zij haar van het evangelie, (2) en moedigt zij het morele elitarisme van christenen aan, wat altijd obstakel is voor het begrip van het evangelie als een belofte van verlossing voor zondaren. Christenen behoren niet te denken in termen van wij en zij. 

## Herhaling

We herhalen in het kort ons dubbele begrip van de Bergrede: als evangelie en als ethiek van het Koninkrijk. Als evangelie van het Koninkrijk is zij kracht van God tot zaligheid. Zij oefent macht uit door ongelovigen tot discipelen te maken. 
De ethiek van de Bergrede is de boodschap van een hogere gerechtigheid. De geestelijke, morele en praktische uitdaging de wil van de Vader te volbrengen, door de  navolging van Christus, in de vorm gehoorzaamheid en geloof,  in de weg van kruis en opstanding. Met deze aantekening dat het moralisme van de Bergrede ook evangelie is, omdat het de honger en dorst naar gerechtigheid doet ontwaken en herleven en belooft te verzadigen. Omdat het een krachtige aansporing tot navolging en volmaaktheid is. 
De historische ervaring bewijst dat geen enkele christelijke stroming, traditie of belijdenis zich de Bergrede volledig heeft kunnen toe-eigenen. Haar evangelische ethiek gaat altijd het morele vermogen van de mens te boven. 

## Oefeningen

1. Hoe waardeert het katholicisme de ethiek van de Bergrede?

2. En het historische protestantisme?

3. En welke gevolgen?

4. Welke pedagogische betekenis geeft het historische protestantisme aan de Bergrede?

5. Hoe waarderen de radicale stromingen de Bergrede?

6. En de liberalen/modernisten?

7. En de evangelicalen?

8. Verklaar het begrip contrastgemeenschap.

9. Welke zijn de bezwaren van de evangelicale waardering van de Bergrede?

10. Wat is het dubbele begrip van de Bergrede dat verdedigd wordt?


