# wijsheid als verantwoordelijk leven 

*De christelijke ethiek stelt de vraag hoe de mens als schepsel van God, maar gevallen in zonde en daarom voorwerp van Gods toorn èn genade, een verantwoordelijk leven kan leiden.  Welke ruimte hebben we tussen de wet die ons veroordeelt en het evangelie dat ons vrijspreekt? Tussen de hoge gerechtigheid die Christus onderwijst in de Bergrede d.m.v. Zijn voorbeeld en uitnodiging tot navolging, en het praktische realisme van de lage gerechtigheid van het leven van iedere dag? We zagen reeds dat de Bijbel ons inderdaad een ruimte voor het goede leven en de moraal aanwijst. Het is de wijsheid. a) We ontmoetten de wijsheid reeds als het Bijbelse begrip voor de ethiek. b) Ook kwamen we haar tegen als één van de eerste en hoogste waarden. c) Nu zullen we de gedachte uitwerken dat zij een geestelijke en morele ruimte schept tussen de wet en het evangelie. Een ruimte die voorwaarde is voor een geestelijk en moreel verantwoordelijk leven.*

## Wijsheid in het Oude Testament

De Wijsheid wordt in het Oude Testament gedefinieerd door de vreze des Heren (Spreuken 1.7*; 9.10; Psalm 111.10). Het is het vermogen om moreel goed en zuiver te leven, door het kwaad te vermijden, het goede te kiezen en de juiste beslissingen te nemen. Door de morele en praktische uitdagingen van het leven aan te kunnen.  Bijbelse wijsheid is weten, door intuïtie en ervaring, door opvoeding en cultuur, door scholing en tucht, hoe je goed kunt leven, in de relatie met God, met je naaste en met jezelf.

Spreuken 1.1-7 biedt een begrip van de Bijbelse wijsheid door middel van een stereometrie van verschillende perspectieven. Wijsheid is het vermogen wijsheid in haar verschillende vormen te onderscheiden, te begrijpen, te verwerven en te delen (2, 3). Wat wordt gecommuniceerd is een traditie van wijsheid. De aangesprokenen zijn in de eerste plaats de wijzen zelf (5) maar ook worden jongeren en onvolwassenen uitgedaagd (4). De wijze gebruikt zijn wijsheid om te onderwijzen en zo ontstaat er een pedagogische relatie tussen generaties (6). De climax van de passage verschijnt aan het eind in 1.7, waar ons gezegd wordt dat het begin, de oorsprong, het oriëntatiepunt van de fundamentele kennis (begrepen als wijsheid) de vreze des Heren is (zie 9:10; Job 28.28; Psalm 111.10; Pred. 12.13). Het blijkt dus dat het Bijbelse begrip van wijsheid niet antropocentrisch is, maar theocentrisch. Het is een moment van geloof dat de ethiek bepaalt, omdat de vreze des Heren bestaat uit het haten van het kwaad, hoogmoed, trots, boze wandel en gedraai (Spr. 8.13).

## Het Spreukenboek
Vervolgens bevestigt het boek Spreuken – het belangrijkste wijsheidsboek van de Bijbel – de waarden en scheppingsordeningen die we in eerdere hoofdstukken al hebben opgesomd en gedefinieerd. De wijsheid in Spreuken wijsheid is pedagogisch. Het boek onderwijst expliciet Bijbelse waarden en deugden in de vorm van wijze raad van ouders en leraren. Het is optimistisch aangaande de morele en spirituele kracht van deze raad om het gedrag van mensen te sturen en te corrigeren, geduldig en begripvol tegenover de jongeren en onvolwassenen die zijn leer waarderen, maar ongeduldig en vijandig tegenover de dwaasheid van de dwazen die het verachten.

## De waarden in Spreuken

    1. GERECHTIGHEID
Op het pad der gerechtigheid is leven, maar de weg der zonde voert ten dode. (Spr. 12.28)
    2. WIJSHEID
Het begin van de wijsheid is de vreze des Heren (9.10)
    3. MOED
De goddeloze gaat op de vlucht, zonder dat iemand vervolgt, maar de rechtvaardige voelt zich veilig als een jonge leeuw. (28.1)
    4. MATIGHEID
… en zet u het mes op de keel, als u een gulzig mens bent. (23.2)
    5. GELOOF/VERTROUWEN
Op haar vertrouwt het hart van haar man, het zal hem aan voordeel niet ontbreken. (31.11)
    6. HOOP
De verwachting der rechtvaardigen is vreugde, maar de hoop der goddelozen gaat teniet. (10.28)
    7. LIEFDE, BARM-HARTIGHEID
Haat verwekt gekrakeel, maar liefde bedekt alle overtredingen. (10.12) Beter een schotel groente waar liefde heerst, dan een gemeste os en haat daarbij. (15.17)
    8. Goedheid
Wie gerechtigheid en liefde najaagt, vindt leven, gerechtigheid en eer. (21.21)
    9. Vrede
Bedrog is in het hart van wie kwaad smeden, maar voor wie tot vrede raden is er vreugde. (12.20)
    10. Bescheidenheid/ootmoed
De vreze des HEREN voedt op tot wijsheid, en ootmoed gaat vooraf aan de eer. (15.33)
    11. Reinheid/zuiverheid
Reeds een knaap laat zich door zijn handelingen kennen, of zijn doen zuiver is en recht. (20.11)
    12. Verantwoor-delijkheid
Een koning die de geringen naar waarheid richt, diens troon staat voor eeuwig vast. (29.14)
    13. Vrijheid
Doe dan toch dit, mijn zoon, en red u, want u bent in de greep van uw naaste gekomen: ga, klamp uw naaste aan en bestorm hem. (6.3)
    14. Eerbied
Zoals wie een steen in een slinger vastbindt, zo is hij, die een dwaas eer geeft. (26.8)
    15. Beraden
De weg van de dwaas is recht in zijn ogen, maar wie naar raad luistert, is wijs. (12:15)
    16. Eerlijkheid (waarheid)
Beter een arme die in oprechtheid wandelt, dan iemand die verkeerde wegen gaat, al is hij rijk. (28.6)
    17. IJver
Ik heb lief wie mij liefhebben, wie mij ijverig zoeken, zullen mij vinden. (8.17)
    18. Geduld
Door lankmoedigheid wordt de machtige vermurwd, een zachte tong verbreekt beenderen. (25.15)
    19. Dankbaarheid
Rijkdom brengt veel vrienden aan, maar een arme wordt door zijn vriend verlaten. (19.4)
    20. Verstandigheid
 Vertrouw op de HERE met uw ganse hart en steun op uw eigen inzicht niet. (3.5)
    21. Kuisheid
Waarom zoudt gij dan, mijn zoon, afdwalen naar een vreemde, de boezem van een onbekende omarmen? (5:20)
    22. Meer waarden?

## De scheppingsordeningen in Spreuken 
Het recht van God, Zijn exclusieve Naam, Zijn heiligheid en Zijn wil.
Mijn zoon, vrees de HERE en de koning, laat u niet in met oproermakers. (24.21)
Het recht van de schepping (¿Op.11.18?)

Het recht van het leven – menselijk, dierlijk, plantaardig leven.
De rechtvaardige weet wat toekomt aan zijn vee, maar de barmhartigheid der goddelozen is wreed. (12.10)
Het recht van het huwelijk – het is niet goed dat de mens alleen is.
Wie een vrouw vond, heeft iets goeds gevonden en gunst van de HERE verworven. (18.22)
Het recht van de voortplanting en het gezin – de mens wordt geboren in en wordt opgevoed in een gezin.
De kroon der ouden zijn kindskinderen en de eer der kinderen zijn hun ouders. (17.6)
Het recht van eigendom en patrimonium – huis, kleding, voeding, productiemiddelen.
Zij houdt toezicht op de gang van haar huishouding, het brood der traagheid eet zij niet. (31.27)
Het recht van de staat (de georganiseerde samenleving); de mens leeft in gemeenschappen die vertegenwoordigd worden door gevolmachtigde vertegenwoordigers: hoofden, vorsten, leiders, commandanten.
Mijn zoon, vrees de HERE en de koning, laat u niet in met oproermakers. (24.21)
Wie reinheid van hart bemint en wiens lippen vriendelijk zijn, de koning is zijn vriend. (22.11)
Het recht van de economie; productie en consumptie zijn nooit geheel privé-eigendom en evenmin geheel collectief eigendom.
Zij staat op, als het nog nacht is, zij geeft haar huis het voedsel, haar dienstmaagden haar deel. (31.15)  Zint zij op een akker, dan verwerft zij die, van de verdienste van haar handen plant zij een wijngaard. (31.16)
Het recht van de rechtspraak.
Een koning die de geringen naar waarheid richt, diens troon staat voor eeuwig vast. (29.14)
 Het recht van rust.
Indien gij u neerlegt, zult gij niet opschrikken, maar gij zult u neerleggen en uw slaap zal zoet zijn. (3.24)

## Oefeningen

1. Welke zijn de drie betekenissen die de Bijbel geeft aan het begrip wijsheid?

2. Door welk principe wordt de wijsheid in het Oude Testament bepaald?

3. Waarom wordt Spr. 1.1-7 een stereometrie genoemd?

4. Leg uit dat de Bijbelse wijsheid niet antropocentrisch, maar theocentrisch is.

5. Leg uit dat de Bijbelse wijsheid – dus de Bijbelse ethiek – pedagogisch is.

6. Wie zijn de wijzen en wie zijn de dwazen in Spreuken?
