# DE WIJSHEIDPEDAGOGIEK VAN SPREUKEN 


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*Meestal onderscheiden we in de Bijbel twee verschillende wijzen waarop het Woord van God zich tot de mens richt: door de wet en door het evangelie. Echter, we moeten deze indeling aanvullen met een derde, even Bijbelse wijze van aanspreken, namelijk die van de wijsheid. Terwijl de wet ons veroordeelt vanwege onze zonde en het evangelie ons vergeving van zonden belooft vanwege het offer van Christus, biedt wijsheid ons een ruimte om moreel en geestelijk goed te leven, in de vreze des Heren.*

*Wijsheid is een integraal onderdeel van de hele Bijbel, zowel van het Oude als het Nieuwe Testament, maar concentreert zich in de wijsheidsboeken Spreuken en Prediker. In dit hoofdstuk vervolgen we de ethiek van Spreuken door enkele representatieve passages uit het boek samen te vatten.*

## Wijsheid is een geschenk van God 

Wijsheid in de Bijbel komt van God en is een geschenk van God.  In Spreuken 8 wordt zij voorgesteld als een hemelse prinses (zie Spr. 1:20-33; 3:13-20; hfst. 9), een directe getuige van de oorsprong van alle dingen omdat zij in de schepping de Schepper vergezelde en bijstond met haar bekwaamheid en enthousiasme (22-36). Dus is zij een gepersonifieerde eigenschap van God, voorgesteld als een grande dame, wier naam we met een hoofdletter schrijven, die de publiciteit zoekt en waarheid en geloofwaardigheid biedt (7-8). Een speciale relatie heeft zij met de politieke heersers, die door haar macht uitoefenen (12-16). Aan het einde van het boek ontmoeten we haar als een deugdzame vrouw, die een projectie is van goddelijke Wijsheid in het dagelijkse leven (Spr.31:10-33). 

## De instructies van vaders, moeders en leraren 

De Wijsheid in Spreuken inspireert ouders en leraren bij de opvoeding van hun kinderen, waarbij er geen principieel verschil is tussen de instructies van ouders en die van God – de Heilige Geest – in het geweten. Wat de Wijsheid onderwijst is haar eigen wijsheid, het vermogen om goed te leven in de praktijk van het leven, in de vreze des Heren door het respecteren van de waarden, het nastreven van deugden en zuivere motieven. 

## Een waarschuwing (Spr.1.8-19)

De eerste ouderlijke instructie in het boek Spreuken - inderdaad, in naam van beide ouders (8) - weerspiegelt het wereldbeeld van de wijze mannen van Israël. De wereld is vol gevaren en de mens, vooral de jongere, staat bloot aan haar verleidingen. Het kwaad is misleidend, omdat het dingen belooft die het niet waar kan maken. Als iemand zich laat verleiden door het kwaad, is er geen weg terug. 

De Wijsheid heeft geen behoefte het kwaad te wreken, of zelfs maar te straffen, omdat zij ervan overtuigd is dat het zijn eigen ondergang bewerkt. Zij is niet idealistisch, noch pessimistisch, maar realistisch. Het kwaad bestaat en de Wijsheid wapent zich ertegen en wijst op de negatieve gevolgen ervan. Het is de verantwoordelijkheid van ieder mens, vooral van jongeren, om afstand te houden tot het kwaad en niet het verkeerde pad op te gaan. 

## De Wijsheid beschermt

Spr.3.1-12 richt zich tot de jongere en moedigt hem aan, op een vriendelijke en hartelijke toon, de deugd te betrachten. Laat hem altijd afstand houden van het kwaad (7), laat hem altijd trouw en vriendelijk zijn, God vrezend (3.4.7). Laat hem nederig zijn, van ganser harte vertrouwen op de Here, Hem altijd raadplegen (5). Laat hem de tucht van de Here aanvaarden, want Hij tuchtigt degene die Hij liefheeft, zoals een vader zijn zoon tuchtigt (12). Laat hem zijn verplichtingen tegenover God nakomen (9). Hetzelfde vaderlijke vermaan geeft concrete voordelen: de jongere die gehoorzaam is, zal de gunst van God en de mensen krijgen en gezegend worden met vrede, gezondheid en voorspoed (2, 4,8,10). 

## Vier vaderlijke vermaningen

Spr. 6.1-19 bestaat uit vier vermaningen tegen verschillende ondeugden in de vorm van een climax. De eerste twee beschrijven hoe men zichzelf te gronde richt door lichtvaardigheid en luiheid. De laatste twee gaan over de gemeenschap waarvan de orde - ingesteld door de Here - in gevaar gebracht wordt door onwaardige goddelozen. 

1. Lichtzinnigheid (Spr. 6.1-5); De Wijsheid observeert het gevaar van lichtvaardige borgstelling voor een ander (zie Spr. 11.15; 17.18; 20.16).
	
2. Luiheid (Spr.6.6-11); De luiaard is een trieste figuur, die bang is de kansen van het leven te benutten. Hij is asociaal en onverschillig. Er is geen toekomst voor hem, want hij vertrouwt niet op de Wijsheid. De verachting van Spreuken voor luiheid wordt samengevat in het bekende Ga tot de mier, gij luiaard, zie haar wegen en word wijs (Spr.6.6). 

3. Onwaardigheid (Spr.6.12-15); De onwaardige, de adam-belial manipuleert, lokt uit en brengt het kwaad voort. Zijn hart is de bron ervan, maar al zijn leden werken mee: zijn mond, zijn ogen, zijn voeten. De straf van de goddeloze is inherent aan zijn onwaardige leven. 
 	
4. Gruwelen; Zes afschuwelijke dingen haat de Here, maar het zijn er nog één meer en het zouden er nog wel veel meer kunnen zijn (zie voor de getalspreuken Spr. 30:18, 21, 29; Job 5:19; Ps. 62:12; Am. 1:3; 1:6; 1:8; 1:11;2:1; 2:4; 2:6; Jer. 3:14). De afschuwelijke dingen, de ondeugden, de waardeloosheid, die de Here haat zijn hoogmoed, leugen, geweld, boze opzet, valse getuigenis en tweedracht. We kunnen aan deze lijst toevoegen het bederf van hart (Spr.3 .32; 11.20), goddeloosheid en gebrek aan vroomheid (Spreuken 8.7; 15.8,9 26; 17.15; 21.27), bedrog en leugenachtigheid (Spreuken 11.1; 20.10,23; zie Spreuken 12.22; 16.5; Deut. 7.25-26; 12.31; 23.18; 22.5; 27.15).

## Instructies aangaande het huwelijk

In Spreuken is de huwelijksrelatie type van alle gezonde, bevredigende en vruchtbare relaties. De deugdzame vrouw is de personificatie van wijsheid (31.10-31; 9.1-6), terwijl de vreemde vrouw de personificatie van dwaasheid is, of ze nu een prostituee is of de vrouw van een andere man (5; 6.20-7.27; 9.13-18). Tegelijk moeten we de teksten over het huwelijk en de relatie tussen man vrouw letterlijk lezen: als advies van de wijzen aan de jongeren. 
	
Spreuken, net als heel het Oude Testament en vooral het boek Hooglied van Salomo, bevestigt de erotiek en markeert de ruimte ervan binnen het huwelijk, dat een monogame, intieme en bevredigende relatie is, zelfs zonder dat de de voortplanting genoemd wordt (5.15-20). Erotiek buiten het huwelijk is gevaarlijk en destructief (Spr.5.3-14; 6.20-35; 7.1-27). Vanzelf kunnen we de vermaningen ook omgekeerd toepassen. De overspelige vrouw wordt dan de overspelige man, de onrijpe jonge man de onrijpe jonge vrouw (7.7) en de deugdzame vrouw de deugdzame man (31), zodat ook huwelijkstrouw wederzijds wordt, toch is het perspectief meer mannelijk dan vrouwelijk.

Van belang is voor onze tijd dat Spreuken geen andere seksualiteit dan die tussen man en vrouw in een monogame relatie. Verleiding is de gevaarlijke gedachte dat gestolen water zoet is, en in het geheim gegeten brood smakelijk (9.17; 7.10-27), maar misschien is overspel nog gevaarlijker dan prostitutie. Spreuken erkent de wraakgevoelens van de bedrogen echtgenoot (6.26-35). 

## Zuiverheid van motieven
Welk advies is relevanter voor de jongeman van alle tijden en ook voor alle ouderen dan dat van Spreuken 4.23 over de reinheid van ons hart: Behoed je hart boven al wat te bewaren is, want daaruit zijn de oorsprongen van het leven. We moeten voorzichtig zijn met ons hart, met wat we denken, voelen en willen. We moeten onze ideeën en gedachten, onze emoties en onze beslissingen onder controle hebben, omdat ze ons leven vormgeven. En de zelfbeheersing is altijd gemotiveerd door het zelfde principe: de vreze des Heren.

## Oefeningen

1. Welke zijn de drie wijzen waarop de Bijbel, Oude en Nieuwe Testament, ons aanspreekt?

2. In welke boeken concentreert zich de Bijbelse wijsheid?

3. Waarom is wijsheid een genade?

4. Op welke wijze treedt de Wijsheid op in Spr.8?

5. Wat is de relatie van de Wijsheid met de machthebbers in Spr. 8?

6. Op welke wijze verschijnt de Wijsheid in Spr.31.10-33?

7. Welke twee vormen van wijsheid komen samen in het Bijbelse begrip van wijsheid?

8. Wat onderwijst de Wijsheid?

9. Waarom straft de Wijsheid niet actief de dwaasheid?

10. Welke is de beschermende macht van de wijsheid?

11. Hoe richt een mens zichzelf te gronde?

12. Leg uit waar lichtzinnigheid toe leidt.

13. Waarom veracht de wijsheid de lichtzinnigheid en de luiheid zozeer?

14. Beschrijf de onwaardigheid.

15. Wat is de betekenis van zes dingen, ja zeven?

16. Welke zijn die zes die er wel zeven en nog veel meer zouden kunnen zijn?

17. Waarvoor staat de verhouding man-vrouw model?

18. Waarvoor staan de deugdzame vrouw en de overspelige vrouw model?

19. Hoe waardeert Spreuken de erotiek?

20. Waarom en op welke wijze moeten we voorzichtig zijn met ons hart?

