# DE WIJSHEID VAN PREDIKER EN VAN HET NIEUWE TESTAMENT 


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*Wijsheid is in de Bijbel meer dan één van de kardinale waarden. Het is de Bijbelse ethiek zelf en tegelijkertijd een morele en geestelijke ruimte tussen de wet die veroordeelt en het evangelie dat vergeving belooft. In de wijsheidsboeken heeft de Bijbelse ethiek een eigen vorm, naast die van de wet en van het evangelie. We hebben reeds een synthese gegeven van de optimistische pedagogische ethiek van het boek Spreuken, we gaan nu verder met de ethiek van het boek Prediker. Een pessimistische ethiek die wanhoopt aan de mogelijkheid om goed te leven, maar die niet toegeeft aan onverschilligheid en cynisme vanwege het geloof in God. Aan het einde zullen we de wijsheid van het Nieuwe Testament kort samenvatten. *

## IJdelheid der ijdelheden ... 

IJdelheid der ijdelheden, alles is ijdelheid, met deze donderslag van woorden ontkent de Prediker de zin van het menselijk leven, van de geschiedenis en van de schepping (Prediker 1.1-11; 4.7-12). Rijkdom maakt niet gelukkig. Plezier en geluk zijn vals (2; 5.7-6.12). Rouw is beter dan feest (7.1-7). Alles heeft zijn eigen tijd, alles is relatief, tijdelijk en voorlopig (3.1-15; 9.7; 11.3). Zelfs wijsheid helpt niet, want wie kennis toevoegt, vermeerdert het verdriet en het lot van de wijze en de dwaas is hetzelfde (1.12-18; 7.23-29; 9.1-12; 11.12).  Het leven is verschrikkelijk (2.17), de doden zijn beter af dan de levenden, zelfs de ongeborenen (4.2, 3). Menselijk leven is niet beter dan dierlijk leven, want beide treft hetzelfde lot (3.18-22; 12.7).  Het is niet alleen de zinloosheid die de Prediker beangstigt, maar ook onrechtvaardigheid en ondankbaarheid, onverschilligheid en dwaasheid (3.16,17; 4.13-16; 8.10-17; 9.13-10.3). 

Ondanks zijn bijna pathologische pessimisme bevestigt Prediker het leven en de wijsheid. Wijsheid heeft het voordeel boven dwaasheid, als licht boven duisternis (2.13). En een levende hond is beter dan een dode leeuw (9.4). Bovendien weten de levenden dat ze zullen sterven, terwijl de doden niets weten (8.13; 9.5). Het is het geloof in God dat de Prediker uiteindelijk beschermt tegen cynisme en scepsis, omdat God de orde der dingen heeft ingesteld die hij ervaart als ijdelheid en onrechtvaardigheid (1.13; 3.10-18; 5.1-6; 5.18-6.10;7.12-14). Hij rechtvaardigt God door te zeggen dat Hij de mens rechtschapen heeft gemaakt, maar de mensen hebben veel bedenkselen gezocht (7.29). Op deze manier behoudt de Prediker midden in zijn crisis van waarden een basis voor de ethiek. De conclusie van het hele betoog is deze: Vrees God en onderhoud zijn geboden, want dat is de hele mens (12.13). 

## Een eigen pessimistische ethiek 

De conclusie waar we toe kwamen, staat de Prediker toe een reeks duidelijke instructies te formuleren, die vergelijkbaar zijn met Spreuken. De waarden die hij voorstaat zijn vreze des Heren, nederigheid, voorzichtigheid, integriteit, geduld, realisme (5.1-7; 7.8-14; 8.1-9). Hij betreurt de minachting van de wijsheid (9.13-10.3) en waarschuwt tegen onverantwoordelijkheid, luiheid, lichtzinnigheid, omkoping en roekeloosheid (10.16-20). Hij prijst vrijgevigheid en goede investeringen, moed in het ondernemen en toewijding (11.1-6). Het advies aan de jongeren is zich te verheugen in hun jeugd en tegelijkertijd serieus te leven vanwege het komende oordeel, want God zal elke handeling samen met alles wat verborgen is, goed of kwaad, in het oordeel brengen (11.7-12.14).   

Het is in Prediker 7.15-22 waar de schrijver komt tot een eigen ethiek. Vanuit zijn diepe pessimisme (15) beveelt hij het aan om in complexe situaties verschillende opties open te houden (18), te vertrouwen op wijsheid in plaats van macht, ongevoelig te zijn voor negatieve opmerkingen (22). Hij beveelt zelfs een delicaat moreel evenwicht tussen goed en kwaad aan: Wees niet te rechtvaardig, noch te wijs, waarom zou je jezelf vernietigen? Wees niet te slecht, noch te dwaas; waarom zou je sterven voor je tijd (16,17). Bijna het bekende evenwicht in de ethiek van Aristoteles en een echo van het pragmatisme van latere eeuwen. 

## Wijsheid in het Nieuwe Testament
	
Hoewel de wijsheid in het Nieuwe Testament geen eigen literaire vorm heeft, zoals in het Oude Testament, zet zij wel de Oudtestamentische traditie voort. De Wijsheid is nu de wijsheid van Christus, geopenbaard in de evangeliën en apostolische brieven en tegelijk één van Zijn belangrijkste eigenschappen (Matteüs 13.54; Markus 6.2; Lukas 2.20, 52; 1Cor.1.24, 30). De wijsheid van Christus contrasteert met de wijsheid van deze wereld, die vijandig staat tegenover Hem en zijn evangelie (1Co.1.17-24; 2.5; 3.19; 2Co.1.12; Jakobus 3.15). In de Bergrede vinden we elementen uit de wijsheidstraditie van het Oude Testament overgebracht naar het Nieuwe en in Handelingen 6.10 verschijnt wijsheid als een gave van de Heilige Geest. 

## Wijsheid in de brieven 

Ook in de apostolische literatuur vinden we geestelijke, morele en praktische instructies die sterk lijken op de wijsheid van het Oude Testament. Hun gezag is niet zozeer volgens de wet, die eist en veroordeelt, noch volgens het evangelie, dat vergeving belooft, maar vooral pedagogisch. Ze beweegt zich in dezelfde morele ruimte als de wijsheid van het Oude Testament, tussen de wet en het evangelie, waarin de discipelen hun eigen verantwoordelijkheid hebben. We herkennen deze pedagogiek in Kol. 1.28 waar Paulus ieder mens vermaant en ieder mens met alle wijsheid onderwijst, om ieder mens volmaakt in Christus te doen zijn. In Kol. 3.16 gaat het erom elkaar in alle wijsheid te onderwijzen en te vermanen. Jakobus begrijpt de wijsheid door de waarden van vrede, tolerantie, zelfgenoegzaamheid, barmhartigheid, onpartijdigheid en integriteit (Jakobus 3.17). 

In feite zijn alle apostolische brieven, bij dat ze de christenen uit de eerste eeuw de fundamentele waarheden van het geloof in Christus in herinnering brengen, pastorale aansporingen tot navolging van Christus, die de stijl van wijsheid gebruiken om de waarden en deugden aan te prijzen die de christelijke ethiek vormgeven. De duidelijkste voorbeelden van de pastorale en pedagogische wijsheid van de apostelen zijn Rom. 12.9-15.6; Ef.5.21-6.9; Kol.3.18.4.1; 1P. 2.11-3.7 en de hele brief van Jakobus. We kunnen ook Paulus' onderwijs over de vrucht van de Geest en de werken van het vlees ook begrijpen in termen van wijsheid en ethiek (Gal.5.20-22). 

## De wet van vrijheid

Bijbelse ethiek is wijsheid. Ze is op juiste wijze leven, in de vreze des Heren, in de verhouding met de naaste en ieder met zichzelf. Zij is praktisch omdat zij ons leert in de natuurlijke verhoudingen, als burger van deze wereld, de juiste beslissingen te nemen. Bijbelse wijsheid heeft haar eigen vorm in de wijsheidsboeken van het Oude Testament en in de wijze raadgevingen in andere boeken van het Oude en Nieuwe Testament. Ze bevestigt dezelfde waarden als de wet en het evangelie, maar creëert een eigen ruimte tussen beide. De ruimte om verantwoordelijk te leven, is volgens de wet van de vrijheid (Jakobus 1,25; 2,12). Zelfs kunnen we zeggen dat de wijsheid deze wet van de vrijheid is. 

## Oefeningen
1. Leg opnieuw uit dat de Bijbelse ethiek wijsheid is.

2. Wat is het verschil in stemming tussen Spreuken en Prediker?

3. Benoem het pessimisme van Prediker.

4. Hoe bevestigt Prediker ondanks alles het leven en de wijsheid?

5. Wat beschermt Prediker tegen cynisme en scepsis?

6. Hoe rechtvaardigt Prediker God?

7. Welke basis vindt hij voor zijn ethiek?

8. Welke waarden verdedigt Prediker?

9. Welk advies geeft hij aan jongeren?

10. Waar en hoe komt Prediker het dichts bij een eigen ethiek?

11. Welke ethische systemen herkennen we in de ethiek van Prediker?

12. Welke verhouding heeft de Bijbelse wijsheid met Christus?

13. Waar vinden we de Nieuwtestamentische wijsheid?

14. Leg uit dat de wijsheid in de apostolische brieven praktisch en pedagogisch is?

15. Leg uit de verhouding tussen de wijsheid en het pastoraat in de apostolische brieven?

16. Leg uit de verhouding tussen de wijsheid en de wet van de vrijheid.




