# DE HEILIGE GEEST EN HET GEWETEN


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*De waarden die we bestuderen als coördinaten van de ethiek, maken deel uit van Gods goede schepping en bleven van kracht, ook toen de mens door de zonde van God gescheiden werd, in de voorzienigheid als natuurrecht of natuurwet: het natuurlijke weten van goed en kwaad, van waarde en onwaarde, van deugd en ondeugd. In de Bijbel worden dezelfde waarden onthuld, bevestigd, onderwezen en gepreciseerd in de vorm van Wet, Evangelie en Wijsheid. De wet spreekt ons aan als dienaren van God, het evangelie als discipelen van Christus en de Wijsheid als verantwoordelijke burgers van deze wereld. De geestelijke en natuurlijke wijsheid van de mens, om in geestelijke en natuurlijke zin goed te leven, worden door de Bijbel toegeschreven aan de Heilige Geest.*

## De voorzienigheid
De voorzienigheid is het besluit van God na de zonde de schepping te bewaren, met het oog op haar redding en op het herstel van alle dingen. De voorzienigheid is genade, want wij verdienen haar niet. Algemene genade, omdat ze het geduld en de barmhartigheid van God bepaalt jegens heel Zijn schepping, vooral jegens de mens, die onderworpen is aan de ijdelheid (Rom.8.20). Zij is een voorlopig levensreddend besluit van God dat de schepping in stand houdt, zonder haar definitief te verlossen. Zij neemt de zonde niet weg, maar veronderstelt en ondersteunt wel de zaligmakende genade door Jezus Christus. 

## De Heilige Geest beperkt het kwaad 
Zoals alle werken van God, is de voorzienigheid volgens een besluit van de Vader, vervuld door de Zoon en gerealiseerd onder de voorwaarden en in de omstandigheden die bepaald worden door de Heilige Geest. Ook in de sfeer van de voorzienigheid heeft de Heilige Geest directe toegang tot het hart, zodat Hij het denken en het handelen van ieder mens kan beïnvloeden, van gelovigen en ongelovigen. Het hart is het geweten, het intuïtief weten van goed en kwaad, een bewustzijn van waarde en onwaarde, waarheid en leugen, recht en onrecht. Door het geweten is de mens wet voor zichzelf, ook al kent hij de geopenbaarde wet van God niet (Rom. 2.14). 
	
De Heilige Geest twist met ons in ons geweten, Hij vermaant ons in het geweten vanwege het kwaad (Gen. 6:3 in SV; Neh.9.30). Als de Heilige Geest niet meer inwerkt op de mens, verhardt of verliest hij zich in het kwaad. Toen de Geest van God wegging van koning Saul, werd deze gekweld door een boze geest van Godswege. Deze boze geest van Godswege is het eigen ongemak, de eigen wanhoop en het eigen gevoel van zinloosheid vanwege de afwezigheid van de Heilige Geest. In dit geval van Saul, omdat hij Gods gunst had verloren (1 Sam 16.14-16, 23; 18.10). In 2Thess. 2.7 is de Heilige Geest waarschijnlijk degene die momenteel nog tegenhoudt, het mysterie van de ongerechtigheid, wat betekent dat de hele duivelse vernietigende kracht van het kwaad zich nog niet volledig had of heeft kunnen ontplooien. 

De aanwezigheid van de Heilige Geest in het geweten van alle mensen is onze natuurlijke morele wijsheid, intelligentie en scherpzinnigheid. We ervaren dat deze aanwezigheid niet constant is en niet stabiel, dat wil zeggen niet bij iedereen gelijk en niet gelijk gedurende het leven. Karakter, opvoeding, leeftijd, omstandigheden en ervaringen en ook de omringende cultuur en de tijd waarin we leven zijn van invloed. Ze werken de Heilige Geest tegen òf worden juist door Hem aangewend. In de sfeer van de bijzondere genade vernieuwt de Heilige Geest – door het geloof in Jezus Christus – het geweten, Hij wekt het op, maakt het actief, en blijft twisten met de discipelen  van Christus in hun geweten vanwege de nog steeds actieve zonde, leugens, hardheid, onreinheid en onverantwoordelijkheid.

## De Heilige Geest stimuleert het goede
De Heilige Geest stimuleert de wijsheid, d.w.z. Hij stimuleert de waarden, de zuiverheid van de motieven en van de deugden en Hij geeft gaven. Het zorgde ervoor dat bepaalde oudtestamentische koningen, die in hun hart niet volkomen trouw aan God waren, evenwel goede regeerders waren: Jehu, Joas en Amazia en ook Cyrus, de Perzische koning.  Rom. 2.14 zegt dat de heidenen die de wet niet kennen, de inhoud van de wet op natuurlijke wijze in praktijk brengen, omdat zij wet voor zichzelf zijn. Lukas 6:33 bevestigt dat zondaars (zij die God niet vrezen) goede en waardevolle medemensen kunnen zijn. Het Oude en Nieuwe Testament schrijven de persoonlijke, culturele, politieke, economische en sociale kwaliteiten en gaven van heidenen en ongelovigen toe aan de Heilige Geest (zie Ex.28.3; 31.1-6; 1S.11.6; 16.13-14; 1R.7.14; Is.28.24ss.; 1Cor.12.4ss). We ervaren dat er invloed uitgeoefend wordt op ons geweten en onze gemoedstoestand en deze invloed wordt in het Oude Testament beschreven als een toestand van de geest – het menselijke geestelijke leven. Op deze wijze begrijpt het Oude Testament ook het morele gedrag als een geestelijke houding (zie Job.15.13; Ps.32.2; Ps. 51.10; 16-17; Jes.29.24; Mal.2.14-15). 

We zagen reeds dat de Heilige Geest toegang heeft tot het hart van ieder mens. Hij is God in ons. Hij geeft het leven en wij leven; Hij leidt ons leven en wij leven deze leiding in geestelijk, moreel en praktisch opzicht (Johannes 6.63). Het zichtbare effect van dit door de Heilige Geest geleide leven in het leven van de gelovigen heet vrucht van de Geest. Deze vrucht van de Geest is hetzelfde waardensysteen als dat wat reeds in de schepping ligt. Dus de waarden die wij door de natuurwet kennen, die door de geopenbaarde wet, door het evangelie en door de wijsheid worden aanbevolen en door de Geest worden gestimuleerd. De waarden die Paulus noemt als vrucht van de Geest zijn: liefde, blijdschap, vrede, lankmoedigheid, vriendelijkheid, goedheid, trouw, zachtmoedigheid, zelfbeheersing (Gal.5.22). 

## Het bedroeven en uitdoven van de Geest
Als wij tenminste de Heilige Geest niet bedroeven door ons te verharden in het kwaad (Jesaja 63.10; Ef.4.30). Zoals wij al eerder zagen (hoofdstuk 4,5), is de verharding het moment waarop wij niet luisteren naar wet, evangelie en wijsheid en evenmin naar ons geweten - als dat tenminste nog ons morele kompas is, want in het proces van de verharding verliest het geweten gaandeweg zijn functie - en dus ook niet naar de Heilige Geest. Deze ongehoorzaamheid is het bedroeven van de Heilige Geest (Jesaja 63.10; Ef.4.30). Zelfs kunnen we Hem tot zwijgen brengen. Als het zover is, gaat iemand met een volkomen gerust geweten en in volle overtuiging voort op de weg van het kwaad. Hij verliest zich in het kwaad, zodat er – bijna - geen terugkeer meer mogelijk is (Hebreeën 6.4-8; 10.26-31). Als Bijbel zegt dat God mensen verhardt, betekent dit dat de verharding van Godswege komt als gevolg van en straf op de zonde, doordat de Heilige Geest niet meer waarschuwt, niet meer met ons twist, niet meer inwerkt op het geweten (Ex.9.12; 10.20,27; 14.8; Deut.2.30; vergelijk Ex.7.13, 22; 8.19; 9.35; 2Kro. 36.13; Daniel 5.20; 1Tes.5.19). Er treedt gewenning op. Het kwaad en de zonde worden gemakkelijk. Ze worden tot een gewoonte en een patroon in het leven, soms zelfs een verslaving. In feite wordt dan zonde met zonde gestraft, kwaad met kwaad. Het einde is de zonde tegen de Heilige Geest, een bewuste, opzettelijke en volgehouden keuze voor het kwaad en de duisternis. Een opzettelijk en bewust ingaan tegen de Heilige Geest, waarbij soms zelfs het werk en de genade van de Heilige Geest duivels genoemd kunnen worden.  Jezus waarschuwt dat er voor deze vorm van zonde geen vergeving mogelijk is (Mattheüs 12.22-32).  

## Collectieve verharding
De verharding kan collectieve en culturele vormen aannemen als een samenleving of een cultuur haar morele en ethische reserves en tradities afwijst en het waardesysteem onderwerpt aan nieuwe, vaak ontwrichtende prioriteiten. Dit gebeurde in Frankrijk ten tijde van de revolutie (1789), toen de individuele vrijheid de hoogste prioriteit kreeg en toen de bewarende krachten machteloos werden gemaakt onder het slogan van geen god en geen meester. De communistische revoluties van de XX eeuw verhieven het gelijkheidsbeginsel tot hoogste principe en schonden de vitale principes  van persoonlijke verantwoordelijkheid en eigendom, terwijl het nazisme de waarde van het ras doorslaggevende en vernietigende betekenis gaf. Het liberale Europa en Noord-Amerika van de XX en XXI eeuw geven absolute prioriteit aan de persoonlijke gevoelens en emoties die bevrijd moeten worden van alle vormen van patriarchaal toezicht, zodat ieder zichzelf kan zijn, ook in moreel opzicht.  Wanneer het onderwijs, de wetenschap en de media in dienst gesteld worden van de bevrijding van wat onderdrukkende waarden heten, treedt de verharding van de cultuur en de samenleving in, waardoor goed en kwaad niet meer kunnen worden onderscheiden. 

## Oefeningen
1. Definieer de voorzienigheid Gods.

2. Verklaar de voorzienigheid als algemene genade.

3. Wat betekent het dat de Heilige Geest toegang heeft tot het hart van ieder mens?

4. Welke plaats heeft de Heilige Geest in de voorzienigheid?

5. Wijs de werking van de Heilige Geest op het geweten aan.

6. Wat betekent het dat  de Heilige Geest twist met de mensen (Genesis 6.3)?

7. Wat betekent het dat een boze Geest van Godswege koning Saul teisterde?

8. Wie is het die hem weerhoudt in 2Tes. 2.7?

9. Leg uit op welke wijze de Heilige Geest het kwaad beperkt.

10. Hoe legt het Oude Testament de gemoedsstemmingen, de intelligentie en de motivatie van bepaalde mensen uit?
 
11. Hoe stimuleert de Heilige Geest het goede in de mens?

12. Leg Rom.2.14 uit als algemene genade, als natuurrecht en natuurwet.

13. Waarom is het zo gevaarlijk als wij volharden in het kwaad?

14. Welke rol speelt de Heilige Geest in de verharding?

15. Leg uit wat de zonde tegen de Heilige Geest is.

16. Leg uit wat collectieve verharding is en geef voorbeelden.


 
	


               