# DE BIJBELSE WAARDEN IN HUN PRACTISCHE VORM 


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*De coördinaten van de ethiek zijn de waarden, die ook verschijnen als normen, regels, motieven, deugden, wetten en rechten. Ze zijn deel van de schepping en de voorzienigheid. In de Bijbel, in het Oude en Nieuwe Testament worden ze onthuld, bevestigd en gepreciseerd in de vorm van wet, evangelie en wijsheid. *
*In de voorgaande hoofdstukken hebben we regelmatig lijsten van de waarden gepresenteerd: de vitale, sociale en ‘grote of hogere’ waarden, die in combinatie met de pure en abstracte waarden verschijnen als praktische waarden in ons leven. We bieden nu een lijst aan met de voornaamste praktische waarden in hun Bijbelse vorm, met de bijbehorende definitie.  *

1. Vreze des Heren; Het begin van wijsheid is de vreze des Heren (Spr. 9.10; 1.7). Wijsheid in de Bijbel is weten hoe je goed moet leven. Daarom is het allerbelangrijkste voor een goed leven, God te vrezen, wat inhoudt dat we Hem respecteren, gehoorzamen en liefhebben (Deut. 6.24; 10.1). Hem lief te hebben met heel het hart, met heel de ziel en met heel het verstand, als eerste gebod(Mattheüs 22.37). 

2. Het tweede gebod, dat evenwel van hetzelfde gewicht is, is het liefhebben van de naaste als onszelf (Mattheüs 22.39). Een gebod dat zijn climax vindt in het liefhebben van de vijand (Mattheüs 5.42,43).  

3. Liefde voor het leven; Egypte had een doodscultuur en een godsdienst gericht op de dood, echter Israël wist dat zijn God niet een God van de doden was, maar van de levenden (Matteüs 22.31). Israël had een levenscultuur en een godsdienst met hoge waardering voor het leven.  De dood werd gezien als een bijster en weerzinwekkend lot. Bovendien was de dood het gevolg van en de straf op de zonde, een scheiding van God, alleen draaglijk als het einde van een goed en vervuld leven (Gen.35.29; 1Chr.23.1, 28; 2Chr.24.15; Job 42.17). Verlossing voor Israël is de verlossing van de dood (Ps.18; 116). Het is de liefde van Israël voor het leven die het geloof in de opstanding voorbereidt. 

4. Politieke en sociale vrijheid; Israël was een volk dat bevrijd was uit de slavernij van Egypte. Deze vrijheid moest altijd verdedigd worden, militair, politiek en profetisch, tegen de omringende volken en rijken en tegen machtsmisbruik van eigen machthebbers (Deut.5.6,15; 1Sam.8). Bijbelse vrijheid is een moreel concept: Israël is vrij om goed te doen, vrij om de wet te houden, maar nooit vrij om kwaad te doen. Wanneer vrijheid de voorwaarde is voor een verantwoorde beslissing, dan is deze beslissing er altijd één van gehoorzaamheid aan de wet (Deut. 4). 

5. Dankbaarheid en liefde; Israël kan zijn leven, welzijn en geluk niet verdienen door de wet te houden, omdat dit leven en geluk al een geschenk van de Here zijn. Zelfs is het houden van de wet het ware leven (Deut. 30,19; 32,47). Het uiteindelijke motief van de gehoorzaamheid is de liefde (Deut. 6.5; 7.9; 11.22; 19.9; 10.12). God niet gehoorzamen uit onverschilligheid wordt God haten genoemd (Deut. 5,9; Rom. 13.10). 

6. Zuiverheid en heiligheid; De wet handhaaft de zuiverheid van het verbond door elke vorm van afgoderij, syncretisme of onverschilligheid te verbieden (1e-4e  gebod). Morele reinheid en heiligheid beschermen de relaties met andere mensen (4e-10e gebod) en voorkomen het verval. Ceremoniële reinheid, alle reiniging van lichaam en kleding, de zorg voor het eten, de hygiëne en de gezondheid is gestalte en type van de morele en geestelijke reinheid. 

7. Gerechtigheid, wet, oordeel, rechtvaardiging; Gerechtigheid is wellicht de belangrijkste waarde van de Bijbelse ethiek (Deut. 16,20). Ze vereist (1) dat iedereen krijgt wat hem toekomt. (2) Wie niet voldoende heeft, heeft het recht geholpen te worden. (3) Het goede behoort beloond te worden, (4) het kwade gestraft, geëlimineerd en/of vergeven, (5) de overtreder gestraft of  geëlimineerd (6) of - indien mogelijk – verzoend en gerechtvaardigd (Lev. 16; 23.26-32; Rom.4.5; 5.1; Gal.2.16; Jak.2.24). 

8. Individuele en collectieve gehoorzaamheid; De werkwoordsvorm van de Decaloog is de toekomende tijd van de tweede persoon enkelvoud, waardoor allereerst de volwassenen aangesproken worden. Met name de patriarchen en anderen met verantwoordelijkheid (vgl. 4e en 5e gebod). Zij zijn verantwoordelijk voor de morele condities van het volk en zij behoren te beseffen dat hun morele beslissingen gevolgen hebben, niet alleen voor henzelf, maar ook voor de volgende generaties. Tegelijk benadrukt de Bijbel individuele verantwoordelijkheid (2e gebod; Jer.13.29; Ezech.18). 

9. Gelijkheid en billijkheid; De Decaloog definieert elke Israëliet als een onderdaan van God, zodat de fundamentele relatie tussen de Israëlieten onderling die van broeders is (zie Deuteronomium 17.15). Alle Israëlieten hebben in principe dezelfde rechten (zie het 4e gebod). Het gelijkheidsbeginsel beschermt ook tegen machtsmisbruik (zie het verhaal van Achab en Naboth in 1R.21).

10. Waarheid; Het gesproken woord moet waar zijn om de gerechtigheid te kunnen handhaven, vooral in het rechtsgeding. Elke persoon heeft de verantwoordelijkheid om zijn naaste te beschermen tegen de leugen (9e gebod; zie 1R.21).

11. Erfenis en eigendom; Het land Kanaän is de erfenis die God als leengoed aan zijn volk heeft gegeven. Elke familie ontving een deel van het land en niemand had het recht zich de de rechten van anderen toe te eigenen. Persoonlijk bezit doet niets af aan de verantwoordelijkheid voor anderen die niets hebben (Ex. 23:11; Deut. 15:11; 24:14; 1Ko.21).

12. Zelfbeheersing; De taal van de Decaloog bevestigt ieders persoonlijke verantwoordelijkheid. In het 10e gebod culmineert deze verantwoordelijkheid in zelfbeheersing. Niet alleen hoererij en diefstal zijn verboden, maar ook het begeren van en het denken aan diefstal en overspel. 

13. Rust, geluk en vrede; De sabbat was de ervaring en het symbool van de vrede die de Here aan zijn volk belooft. Het hoogste ideaal voor Israël was te zitten, ieder onder zijn eigen wijnstok en onder zijn vijgenboom (1R.4.25; Micha 4.4).

Schema 1 – Praktische waarden als combinatie van vitale, sociale en grote waarden met pure waarden

## Oefeningen

1. Herhaal de betekenis van vitale, sociale, en grote waarden, in combinatie met de pure waarden, die als praktische waarden verschijnen.

2. Welke Bijbelse waarden overlappen elkaar op welke wijze?

3. Evalueer de actualiteit van elk van de Bijbelse waarden.