# DE DEUGDEN, VERINNERLIJKTE WAARDEN 


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



De ethiek als begrip van goed en kwaad, is niet subjectief. Het kan niet zo zijn dat ieder van ons kan beslissen welke waarden het leven en het gedrag behoren te bepalen. Het is andersom, de waarden gaan aan ons vooraf. Ze maken deel uit van de schepping. De mens, zelfs de mens die God niet kent, noch de openbaring van de wet, heeft ze in zijn hart (Rom.2.14). Als de waarden traditioneel en cultureel gezag krijgen, zijn het normen, als ze formele regels worden, zijn het wetten (positief recht). Ze hebben echter pas kracht in ons leven als ze verinnerlijkt zijn, als ze deel uitmaken van ons geweten en zelfs van ons karakter. Op dat moment verschijnen ze als motieven (beweegredenen)en deugden. Deugden zijn dus verinnerlijkte waarden, die deel uitmaken van iemands ziel, geweten, hart en karakter, denken en handelen. Het zijn dan de innerlijke principes die gevolgd worden, niet  als een opgelegde plicht, maar vrijwillig, vanuit ieders eigen motivatie. Niet om er beter van te worden, maar omwille van hun eigen waarde. Ze zijn de wet der vrijheid in ons leven (Jak.1.25; 2.12).

## Deugden in het Oude en Nieuwe Testament 

Hoewel het Oude Testament geen eigen woord voor deugden heeft, kent het ze wel als de morele reserves die ons denken, spreken en doen bepalen. Een deugdzaam persoon is een wijs en moedig persoon, die  het vermogen heeft om goed te leven, kansen te benutten, de juiste beslissingen te nemen en moeilijkheden en tegenstand te overwinnen. Wie de deugd veracht is een dwaas, lui en laf. In Exodus 18:21 en 25 kiest Mozes uit het hele volk deugdelijke mannen [mannen van macht], godvrezende mannen, mannen die de waarheid liefhebben en de hebzucht verafschuwen, en geeft hun juridische, politieke en wellicht ook militaire verantwoordelijkheid. In Spr. 31.10-31 verschijnen de deugden als het ideaaltype van de deugdzame vrouw (zie Ruth 3.11; Spr. 12.4). De deugdzame vrouw is inderdaad een compositie van de deugden die zij vertegenwoordigt. Een trouwe en betrouwbare, ijverige, spaarzame, eerlijke, ondernemende, vrijgevige, ordelijke, vooruitziende en uiteindelijk godvrezende vrouw. Vriendin van haar man, zorgzaam voor haar gezin, verantwoordelijk in de samenleving. 

Het Nieuwtestamentische Grieks kent wel een woord voor deugd. In 1P.2.9 komen de deugden naar voren van Hem die uit de duisternis roept tot Zijn wonderbaarlijk licht. Hoewel de tekst ze niet specificeert of definieert, kunnen we Gods deugden begrijpen als Zijn eigenschappen, vooral Zijn waarheid (betrouwbaarheid), liefde, barmhartigheid, geduld en rechtvaardigheid. Vervolgens verschijnen in 2P.1.3 de menselijke deugden als morele uitdagingen. Het geloofsleven is een oproep tot heerlijkheid en deugd (ook macht of kracht) (2P.1.3). Vers 5 van hetzelfde hoofdstuk roept er toe op om aan het geloof deugd en aan de deugd kennis toe te voegen. Dat wil zeggen, om het geloof aan te vullen, compleet te maken, met deugd en met kennis of begrip van God.  Paulus wijst in Fili. 4.8 in algemene termen op de deugden: al wat waar is, al wat waardig is, al wat rechtvaardig is, al wat zuiver is, alles wat lieflijk is, alles van goede reputatie, alles wat lof verdient, alles wat deugd heet. 

## Klassieke en christelijke deugden 

In de Middeleeuwen verscheen er een lijst van deugden die erkend en onderwezen werden door de katholieke kerk. De lijst is een combinatie van de vier kardinale deugden die reeds erkend waren bij en gehanteerd werden door de Griekse filosofie, met drie Bijbelse deugden. Het zijn deze, die we eerder reeds begrepen hebben als waarden: rechtvaardigheid, wijsheid, moed en gematigdheid in combinatie met geloof, hoop en liefde. We kunnen erop vertrouwen dat Paulus, wanneer hij christenen in zijn Brief aan de Filippenzen oriënteert op alles wat waar, eerlijk en rechtvaardig is, enzovoort, verwijst naar deze deugden die in feite de hele ethiek, met alle andere denkbare deugden en waarden, samenvatten. We herhalen dat de deugden verinnerlijkte waarden zijn; waarden die onze eigen drijfveren zijn geworden, die ons handelen van binnenuit bepalen. Misschien kunnen we zeggen: deugden zijn waarden zodra deze bepaald worden door de liefde, liefde tot God en liefde tot de naaste en zelfs liefde voor onszelf in de zin van verantwoordelijkheid voor en betrokkenheid op ons eigen lot. Zonder liefde zijn waarden lege concepten. Met liefde worden ze deugden. 

## Maak de boom goed 

We moeten nog een laatste overweging van groot belang toevoegen: de vermaning van de Here Jezus in Matteüs 12:33: Acht de boom goed, maar dan ook zijn vrucht, of acht de boom slecht, maar dan ook zijn vrucht, want aan zijn vrucht kent men de boom. Eerder heeft Hij hetzelfde al in meer woorden gezegd in Mattheüs 7.17 en 18: Zo brengt iedere goede boom goede vruchten voort, maar de slechte boom brengt slechte vruchten voort. Een goede boom kan geen slechte vruchten dragen, of een slechte boom goede vruchten. Met andere woorden, alleen een deugdzaam mens kan de waarden laten zien die hij of zij verinnerlijkt heeft: rechtvaardigheid, wijsheid, moed en gematigdheid, geloof, hoop en liefde. En hoe duidelijker en eerlijker deze deugden zijn, hoe deugdzamer de persoon is. Tegelijk belijden we nederig dat we Gods vergeving van al onze zonden nodig hebben, met het werk van de Heilige Geest om ons te veranderen van zondige mannen en vrouwen in deugdzame mensen. Zonder Gods genade zijn al onze deugden als vuile kleren (Jes. 64.6). 

## Oefeningen
1. Wanneer worden waarden normen, wetten, motieven (beweegredenen) en deugden?

2. Hoe worden de deugden in het Oude Testament begrepen?

3. Leg de betekenis van de deugdzame huisvrouw uit.

4. Welke relatie hebben de deugden in het Nieuwe Testament met God en met de mens?

5. Welke zijn de klassieke en welke de christelijke deugden?

6. Leg uit de betekenis van de woorden van de Here Jezus over de goede boom en de goede vrucht voor de deugdenleer.



