# HEILIGING ALS MORELE UITDAGING


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*We hebben begrepen dat waarden principes zijn die we altijd hoog moeten houden. In de Schrift komen ze voor in drie vormen. 1) Als wet, als een autoriteit die ons aanspreekt als dienaren van God, die eist en veroordeelt. 2) Als evangelie, een boodschap van bekering, vergeving van zonden en uitnodiging om Christus en Zijn voorbeeld na te volgen als Zijn leerlingen. 3) De derde vorm waarin waarden voorkomen en die een constante is in heel de Schrift, is wijsheid. Wijsheid is weten hoe je goed moet leven in relatie tot God, je naaste en jezelf in het dagelijkse leven, als burger van het Koninkrijk van God, maar ook als burger van deze wereld.  *

*Deze wijsheid is de Bijbelse ethiek. Ze is een geestelijke en morele ruimte tussen enerzijds de wet die haar geldigheid handhaaft, volmaaktheid eist en alles veroordeelt wat niet aan deze volmaaktheid voldoet, en anderzijds het evangelie dat ons bevrijdt van de veroordeling door de wet. Een ruimte waarin ieder zijn eigen morele verantwoordelijkheid draagt. Verder krijgt de Bijbelse ethiek gestalte in de heilige spanning tussen de vrijheid van de wet en de wet van de vrijheid (Rom.7.3; 8.1,2; Gal.4.5; Jak. 1.25; 2.12). De eerste, de vrijheid van de wet, verkondigt dat er geen veroordeling is voor hen die in Christus Jezus zijn, de andere, de wet van de vrijheid, leert ons wat we vrijwillig en in vrijheid moeten doen om God te eren, onze naaste te dienen en tot ons eigen heil. Het blijkt dat Bijbelse ethiek eindigt in heiligheid en heiliging. Als dit doel niet bereikt wordt, heeft ze haar doel gemist. *

## De heiligheid van God 

Heiligheid is één van Gods duidelijkst uitkomende eigenschappen (Zie Psalm 22.3). In Jesaja 6.3 verkondigen de cherubs eeuwig Gods heiligheid, net als de vier levende wezens in Openbaring 4.8. De betekenis van heiligheid is het afgescheiden zijn van, het vrij zijn van alle kwaad, alle corruptie en zelfs van alle vormen van verval en verdorvenheid, en tegelijkertijd een algehele toewijding aan God. Alleen God is geheel vrij van en vreemd aan, ontoegankelijk en onbereikbaar voor alles wat slecht is, voor alles wat verdraaid of bedorven kan worden. Ook is alleen God geheel toegewijd aan God, dat wil zeggen, aan zichzelf. Alle andere heiligheid is van God afgeleid: Zijn heilige woorden (Ps. 105.42; Jer. 23.9), de heilige plaatsen (Ex. 3.5; 29.31), Zijn heilig huis (Jes. 64.11), de heilige ark (2Kron. 35.3), Zijn heilig volk (Ex. 19.6), de heilige berg (Ezech. 20.40), de heilige stad (Neh. 11.18) enz.  Ook de engelen danken hun heiligheid aan God. 

## De heiligheid van Gods volk 

De heiligheid van Gods volk onderscheidt het van wie niet Gods volk zijn. In het Oude Testament werd het Godsvolk apart gezet, om gescheiden van de andere volken te leven. De Israëlieten mochten zich niet vermengen met de volken om niet besmet te raken met hun afgoderij. Het Nieuwe Testament breekt weliswaar de scheidsmuur tussen Joden en niet-Joden af, maar handhaaft dezelfde opdracht als het Oude Testament, namelijk dat Gods volk een heilig volk moet zijn (zie Ex. 19.6; 1Th.4.7; 2Petr. 2.9). Wees heilig want Ik ben heilig, zegt de Here in Lev. 11.44, woorden die herhaald worden in 1Petr. 1.16 (vergelijk Mattheüs 5.48). We weten dat we in onze onvolmaaktheid en zonde de heiligheid nooit op eigen kracht zullen bereiken, maar het is de grootheid en goedheid van God dat Hij Zijn eigen heiligheid met ons wil delen. Hij draagt iets dat alleen Hem toebehoort over aan Zijn schepselen door Zijn Zoon Jezus Christus, die voor ons wijsheid, rechtvaardiging, verlossing en heiliging is (1Co 1.30).

## De heiligheid van Gods volk is zowel passief als actief. 

Zodra we in Jezus hebben geloofd als de Redder en Here van ons leven, heiligt Hij ons.  Hij deelt Zijn heiligheid aan ons mee en maakt ons heilig voor God. Een handeling waarbij we geheel volgzaam en passief zijn. We worden geheiligd, heilig verklaard in Christus. Niet op grond van eigen kwaliteiten, maar vertegenwoordigd door Christus, zijn we volmaakt afgescheiden van het kwaad en toegewijd aan God. 

Tegelijkertijd doopt Christus ons met de Heilige Geest, die in ons werkt en een proces van vernieuwing en heiliging in gang zet dat doorgaat gedurende het hele leven. Dat wil zeggen, de Heilige Geest herinnert ons eraan dat Gods wil onze heiliging is en moedigt ons aan om deze wil van God en onze eigen heiliging in praktijk te brengen, in de weg van bekering en geloof. Wij geloven het evangelie, ervaren de reiniging van ons hart door het geloof en bekeren ons tot een nieuwe en vrijwillige gehoorzaamheid aan God, die ons Christus doet volgen in Zijn gehoorzaamheid aan de heilige wet (Hand. 15.9; 1Thess. 4,3-5). Vrij van de veroordeling van de wet, herinneren we ons de wet van de vrijheid (Jak. 1.25; 2.12), om naar Gods wil vrijwillig te wandelen in goede werken (Rom.8.2; Ef.2.10). Wandelen, leven, alle waarden die de Bijbel ons leert in praktijk brengen. De actieve heiliging die de Heilige Geest stimuleert, valt samen met en bevestigt de passieve heiliging, die we in Christus hebben. Vaak is deze actieve heiliging paradoxaal. Het zal zo moeten zijn dat we minder zonden begaan, dat we stabiele en volwassen christenen geworden zijn, evenwel maakt deze volwassenheid ons veeleisender en preciezer, zodat we meer zonde en onvolmaaktheid in onszelf waarnemen. Dat wil zeggen, juist als we groeien in heiligheid, zorgt diezelfde groei ervoor dat de zonden die we nog steeds vrijwillig of onvrijwillig doen, ons meer pijn doen. 

## Belofte

Uiteindelijk is heiligheid een krachtige belofte aangaande de toekomst. We zullen heilig zijn, geheel vernieuwd in het komende Koninkrijk, waar niets onrein zal binnenkomen, en niemand, die gruwel en leugen doet, maar alleen zij, die geschreven zijn in het boek des levens van het Lam.  Niets vervloekts zal er meer zijn. En de troon van God en van het Lam zal daarin zijn en zijn dienstknechten zullen Hem vereren (Opb 21.27; 22.3). Deze heiligheid is een sterke reden tot blijdschap en vreugde, en lof aan onze God, de Heilige, Heilige, Heilige, Almachtige, die was, die is en die komt (Opb. 4.8).

## Oefeningen
1. Leg uit dat de christelijke ethiek moet uitkomen bij heiliging en heiligheid.

2. Geef inhoud aan het Bijbelse begrip van heiligheid.

3. Wat is de passieve heiligheid van het volk van God?

4. Wat is de actieve heiligheid van het volk van God?

5. Bespreek heiligheid als belofte.


