# DE WAARDENETHIEK VAN C.S.LEWIS


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*Aan het einde van deze hoofdstukken over de ethiek willen we twee auteurs uit de XX eeuw voor het voetlicht brengen, die de christelijke ethiek met al hun overtuiging hebben verdedigd. Het zijn de Britse apologeet C.S. Lewis en de Duitse theoloog, slachtoffer van de naziterreur, Dietrich Bonhoeffer. Beiden diep geschokt door de revolutionaire dynamiek en de zelfvernietigende krachten in de Westerse cultuur. In dit hoofdstuk geven we een korte samenvatting van Lewis' waardenethiek, die in 1943 werd gepubliceerd onder de titel «De afschaffing van de mens». Hetzelfde zullen we doen met Bonhoeffers ethiek van verantwoordelijkheid in het volgende hoofdstuk. *

## Waardenethiek 

De ethiek die we in deze hoofdstukken hebben aangeboden is voornamelijk een waardenethiek. We hebben niet de gedachte toegestaan dat de mens, door naar hoge morele normen te leven, de schepping kan verbeteren, omdat de schepping reeds vanaf het begin goed was. Elk dier is volmaakt het dier dat het moet zijn, elke plant eveneens. Alle zijn ze geschapen naar hun aard. Zelfs de materiële natuur is zoals zij moet zijn: het universum, de sterren, de planeten, de manen en de aarde. Het beste wat de mens kan doen - en niet doet - is de aarde en de schepping bewaren en bewerken en ook zichzelf bewaren (Spr.4.23). We hebben ook niet de gedachte toegestaan dat we onszelf of de mensheid kunnen verlossen, verbeteren of perfectioneren door een juiste ethiek. Gescheiden van God door onze zonde, hebben we vergeving en het werk van de Heilige Geest nodig om verbeterd en vernieuwd te worden. Ondertussen is het beste wat we kunnen doen de waarden, die inherent zijn aan de schepping hoog te houden en te respecteren. Hun juiste definitie aan te houden en ze te gehoorzamen als Gods wil voor ons. Wijze en verstandige verantwoordelijkheid te nemen voor de waarden in de delicate ruimte tussen enerzijds de wet die eist en veroordeelt, en anderzijds het evangelie dat ons vergeving belooft. Tussen enerzijds de praktische gerechtigheid van de menselijke samenleving en anderzijds de hoge gerechtigheid van Gods Koninkrijk. Tussen de oude mens, die we zijn door de zonde en de nieuwe mens die wij hopen te zijn door de genade van Jezus Christus. Tegelijk de waarden zo hoog te achten dat wij ze als deugden verinnerlijken in onze motieven en zelfs in ons karakter. 

## Moreel realisme 

Lewis' hoge waardering van de waarden wordt moreel realisme genoemd. De waarden voor hem zijn geen aannames, maar ze bestaan echt. Ze vormen «een complete, transcendente en immanente verzameling van ware ideeën over goed en kwaad, regels die ontdekt kunnen worden en die ons op gezaghebbende en ondubbelzinnige wijze behoren te leiden om op de juiste wijze te leven». Waarden «initiëren» het leven, en scheppen een veilige en geordende wereld. Ze zijn een geestelijk en praktisch draaiboek voor ons geweten en daarom zouden ze de hoogste inhoud van de opvoeding en het onderwijs moeten zijn. Het morele relativisme daarentegen schept een onbekende wereld. Een wereld waarvan we niet kunnen zeggen hoe zij zal zijn, maar die we moeten vrezen vanwege haar onmenselijkheid.  

## Profetisch 
Als een hedendaagse profeet observeert Lewis de krachtige beweging in de westerse cultuur om de hele natuur te onderwerpen door middel van wetenschap, techniek en ideologieën. Om haar te domesticeren, te manipuleren en haar als grondstof te gebruiken.  Zelfs de mens wordt tot object, tot materiaal. Hij merkt op dat de wetenschap en de ideologieën de mens proberen te onderwerpen aan theoretische projecten, juist door de waarden te veranderen. Lewis is er echter van overtuigd dat de poging de traditionele waarden te vervangen op zichzelf tegenstrijdig is. Er is nooit een radicaal nieuw waardesysteem mogelijk geweest en het zal ook nooit kunnen bestaan. Het is net zo onmogelijk nieuwe waarden te vinden of oude te vervangen als om naast de primaire kleuren rood, blauw en geel nog een andere primaire kleur te vinden. De verschillende culturen geven verschillende inhoud en prioriteit aan de waarden, maar dit ontkent niet dat hun betekenis wordt bepaald door de waarden zelf. Je kunt bijvoorbeeld een bepaald en misschien vertekend beeld hebben van rechtvaardigheid, maar de  rechtvaardigheid zelf zal vroeger of later deze betekenis corrigeren.  

## Mensen zonder hart 

Voor Lewis is het hart de zetel van de waarden. Geen waarden onderwijzen zal tot gevolg hebben dat er mensen zullen zijn zonder hart. Mensen die geen waarden kennen, en geen deugden nastreven, zijn harteloze mensen. Ze zijn niet meer compleet. Ze hebben hun hart dat boven alles wat te bewaren is, niet bewaard (Spr.4.23). Geen waarden onderwijzen is de afschaffing van de mens. Iemand die geen waarden heeft geleerd en ze niet als deugden heeft verinnerlijkt, zal zijn hartstochten nooit kunnen beheersen. Of het nu wil tot macht is of trots, hebzucht of seksuele begeerte, luiheid of fanatisme, minachting of wrok,  hij zal nooit hogere motieven gehoorzamen dan zijn eigen hartstochten. 

Het is opvallend dat Lewis zich niet zozeer ongerust maakt over de revolutionaire ideologieën van zijn tijd, het communisme en het nazisme, die de grootste misdaden in de geschiedenis begingen, maar over de morele leegte en onevenwichtigheid die hij in het UK waarneemt. In feite geeft hij weinig concrete voorbeelden om zijn betoog te illustreren. Misschien waren ze in zijn tijd nog niet zo evident, zodat hij eerder een voorgevoel gehad heeft van wat hij nog niet geheel kon benoemen, dan dat hij feiten heeft waargenomen. Evenwel, wat misschien alleen de meest gevoelige geesten van het midden van de XX eeuw als Lewis intuïtief hebben kunnen weten, is meer dan duidelijk in eigen tijd, de XXI eeuw. 

## Bewijs in onze tijd 

Het is beangstigend hoe onverschillig en zelfs vijandig onze huidige cultuur staat tegenover de traditionele waarden. Ze heeft zelfs het begrip postwaarheid gegenereerd, de overtuiging dat alles in absolute zin relatief is, zelfs de waarheid van feiten en gegevens. Waarden die de stabiliteit van de huwelijken, de gezinnen en de samenleving in stand houden, worden geminacht als patriarchaal, onderdrukkend en seksistisch. De staatswetgeving heeft zich ervoor geleend, op grond van een experimentele antropologie, vitale en hoogstnoodzakelijke sociale waarden te vervangen door nieuwe, feministische, androgyne en inclusieve waarden, waarin de mens niet langer mannelijk en vrouwelijk is, maar een vloeibaar, non-binair wezen. Iemand die zijn of haar eigen seksuele identiteit kan bepalen. Het monogame huwelijk dat door de eeuwen het meest stabiel is geweest, wordt opgeofferd aan modellen die de naam huwelijk niet eens verdienen. De waarde van het leven is relatief geworden door het bizarre recht op de dood, d.m.v. abortus en euthanasie. Tachtig jaar nadat Lewis schreef is het duidelijk dat we zonder waarden geen weerstand kunt bieden aan de verleidingen van consumisme, seksuele losbandigheid, verslavingen en geweld. Zonder waarden kun niemand zijn integriteit bewaren. Voor wie geen waarden heeft, is alles geoorloofd. We zullen zien hoe in deze situatie het strafrecht voortdurend zal moeten worden aangescherpt om de publieke orde te bewaren. Een semi-fascistische almachtige staat ligt in het verschiet, een staat die de ethiek heeft vervangen door wetgeving en strafrecht en die zijn macht op willekeurige wijze zal – kunnen – gebruiken om op te ruimen wat hem in de weg staat. 

Hoe dringend is het om in een relativistische, nihilistische en cynische wereld de vaste en blijvende waarden, onthuld, bevestigd en gedefinieerd door de Bijbelse wet, het evangelie van Jezus Christus en de wijsheid van het Oude en Nieuwe Testament te betrachten en te verdedigen. 


## Oefeningen
1. Leg uit de verschillen uit tussen een waarden- en een deugdethiek.

2. Wat is het culture en sociale motief van zowel C.S.Lewis als van D.Bonhoeffer?

3. Op welke wijze moeten we voorkomen dat de ethiek soteriologie (verlossingsleer) wordt?

4. Waarom verdedigen we een waardenethiek?

5. Leg uit wat het moreel realisme van Lewis is?

6. Wat betekent het dat de waarden toegang geven tot het leven en dat moreel relativisme een onbekende en ontoegankelijke wereld creëert?

7. Wat is het profetische aan de ethiek van Lewis?

8. Welke corrigerende kracht hebben de waarden?

9. Leg de ethiek van Lewis uit met behulp van Spr.4.23.




