# ETHIEK ALS NAVOLGING VAN CHRISTUS, BIJ DIETRICH BONHOEFFER 


<p style='text-align: right;'>*bidden*</p> <p style='text-align: right;'>*het goede doen*</p> <p style='text-align: right;'>*en Gods tijd verwachten*</p> <p style='text-align: right;'> Dietrich Bonhoeffer, 1944</p>



*In het vorige hoofdstuk gaven we een korte bespreking van de waardenethiek van C.S. Lewis, een auteur die zich al in het midden van de XX eeuw grote zorgen maakte over het steeds toenemende ethische relativisme. Lewis spreekt van «mensen zonder hart», mannen en vrouwen die niet langer weten hoe ze hun passies en instincten moeten beheersen of oriënteren door middel van vaste en blijvende waarden. We vullen Lewis' profetische visie op de morele werkelijkheid van onze wereld aan met een samenvatting van de ethiek van de Duitse predikant en theoloog Dietrich Bonhoeffer, zelf in 1945 slachtoffer van de ernstigste morele crises in de geschiedenis, het Duitse nazisme. *

## Leven en werk van Dietrich Bonhoeffer

Dietrich Bonhoeffer werd geboren in 1906, ten tijde van de belle epoche, de glanzende jaren aan het begin van de XX eeuw, toen alle kernlanden van Europa een langdurige bloeitijd beleefden. Europa had een overheersende positie in de wereld, de tweede helft van de XIX eeuw was één van de meest vreedzame perioden in de Europese geschiedenis geweest, er was economische groei door de industrialisatie en door technische en wetenschappelijke vooruitgang. Dit alles gedragen door een geest van optimisme en door grote verwachtingen aangaande de toekomst. Echter ook een tijd van geestelijke en morele malaise en zelfs verveling. «We hebben lang genoeg lief gehad, we willen eindelijk haten», zo werd Europa de Eerste Wereldoorlog in gezongen1. Toen Bonhoeffer in 1923 theologie ging studeren, was er van al het vooroorlogse optimisme niets overgebleven. Het verslagen Duitsland verkeerde in een hevige politieke, economische, maatschappelijke en culturele crisis en werd tien jaar later onderworpen aan het nazisme met zijn tirannieke orde en zijn minachting voor de beproefde waarden. Gehoorzaamheid aan de Führer had de rede vervangen, geweld was in de plaats gekomen van naastenliefde en meedogenloos racisme werd wet. In deze crisis doordacht en ontwierp Bonhoeffer zijn ethiek, die hij door zijn vroege dood als slachtoffer van het nazisme niet heeft kunnen afronden. We vatten haar samen aan de hand van twee van zijn belangrijkste boeken. 

## Navolging 

Het eerste boek van Bonhoeffer dat we willen aanbevelen als een morele en geestelijke gids voor de christelijke kerk van onze tijd is zijn Navolging. Een ethiek voor de discipelen van Christus, op grond van de Bergrede, geschreven in 1937, toen hij directeur was van een clandestien seminarie dat voorgangers voorbereidde op een bediening in de door het regime onderdrukte en vernederde kerk. De uitdaging die Bonhoeffer formuleert voor zijn generatie, en die nog steeds relevant is voor ons, is «hoe Christus vorm krijgt onder ons en in deze wereld». Het hoogtepunt van het boek, al in het eerste hoofdstuk, is de tegenstelling tussen goedkope en dure of kostbare genade. Goedkope genade is die welke de zonde rechtvaardigt, een gevoeligheid die verontschuldiging zoekt voor de zonde op basis van een oppervlakkig evangelie, dat de wet tenietgedaan heeft, een geloof zonder berouw en een vertrouwen op vergeving van de zonde zonder dankbaarheid. Kostbare genade daarentegen is de rechtvaardiging van de zondaar die berouw heeft over alle ongehoorzaamheid aan Gods wet. Gods genade is vooral kostbaar omdat Hij Zijn Zoon heeft moeten offeren voor onze zonden.  Voor ons is zij kostbaar omdat ze navolging van Christus impliceert in vaak ongunstige omstandigheden. In feite is het uiteindelijke gevolg van de navolging van Christus het delen in Zijn lijden. Bonhoeffer aanvaardde dit lijden voor zichzelf. Een maand voor het einde van de Tweede Wereldoorlog werd hij door het regime geëxecuteerd als getuige van Christus en als verantwoordelijk mens in een geschonden wereld. 

## Ethiek

Het tweede boek van Bonhoeffer dat we eveneens aanbevelen is zijn Ethiek, geschreven tijdens de oorlogsjaren, gedeeltelijk terwijl hij in de gevangenis zat. Hij had Joden geholpen de Zwitserse grens over te steken om aan de misdadige staat te ontkomen. Bonhoeffers Ethiek concentreert zich op de waarden van verantwoordelijkheid, vrijheid, vertegenwoordiging en het zich toe-eigenen van schuld. Een christen kan geen toevlucht zoeken in een veilige omgeving, zelfs niet in de kerk, maar hij moet zijn verantwoordelijkheid nemen voor een complexe wereld, in het besef dat de toekomst in zekere zin door hem wordt bepaald, door elke beslissing die hij heeft te nemen en zal nemen. De vrijheid is dat er geen compleet protocol is dat er volledig in voorziet welke beslissingen ieder in elke situatie moeten nemen.  Door verantwoordelijkheid te nemen in de wereld, nemen we haar schuld op ons: het van God afgeweken zijn. Christelijke ethiek wordt gedragen door het besef dat onze persoonlijke zonde de zonde van de wereld vertegenwoordigt en dat onze persoonlijke hoop op Christus de hoop van de wereld vertegenwoordigt. 

## Een praktische ethiek

Verantwoordelijkheid zoals Bonhoeffer haar begrijpt is Navolging van Christus om van Hem de waarden en principes van de christelijke ethiek te leren, om God daarmee en daardoor te gehoorzamen. Later, in zijn Ethiek, is verantwoordelijkheid het vervullen van de roeping van God in in de wereld; het bewaren en verdedigen in de wereld van de fundamentele waarden. Deze ethiek is niet theoretisch, maar één die Bonhoeffer in de oorlogsjaren leefde en in praktijk bracht. Het waren jaren van morele beslissingen die in eenzaamheid genomen moesten worden. Hij leefde gescheiden van de kerk die hij niet langer kon dienen en die hem niet volgde - hij mocht niet in Berlijn wonen, geen onderwijs geven en evenmin preken of publiceren. De clandestiene seminaries waren gesloten, zodat hij ook zijn ideaal van een leven in gemeenschap, een leven van praktische vroomheid, van gemeenschappelijk gebed, voorbede en zelfs biecht, niet langer in praktijk kon brengen2. Paradoxaal genoeg liet hij zich rekruteren door de geheime dienst van de Wehrmacht om in die positie al het mogelijke te doen voor het herstel van de rechtsstaat in Duitsland en Europa na de nederlaag van de nazi's. Zelfs nam hij verantwoordelijkheid voor een aanslag op de Führer. 

## Bidden, het goede doen en wachten op Gods uur

We kunnen Bonhoeffers ethiek samenvatten met de woorden die hij in 1944 aan zijn achterneefje meegaf bij diens doop, als een opdracht en uitdaging: bidden, het goede doen en wachten op Gods uur. Door te bidden zullen we Gods wil in ons leven kennen. Door goed te doen, dat wil zeggen, door God lief te hebben boven alles en onze naaste als onszelf, terwijl we het kwaad weerstaan, zullen we Christus navolgen. Daarbij kunnen we nooit zeker zijn van de effecten van onze daden, omdat die afhankelijk zijn van Gods genade. Wij moeten planten en water geven, maar het is God die de groei geeft (1Co.3.7). Door te bidden, goed te doen en alles van God te verwachten, zullen we alles gedaan hebben wat we kunnen doen. Het zijn deze woorden die we als motto aan deze studies hebben meegegeven. 

## Oefeningen

1. Waarom was het nazisme de ergste morele crisis in de Europese geschiedenis?

2. Leg uit «hoe Christus vorm krijgt onder ons en in deze wereld» als moreel kompas.

3. Leg uit het verschil tussen goedkope en dure genade.

4. Waarom is de genade ook voor God duur?

5. Op welke waarden concentreert Bonhoeffer zich in zijn ethiek en welke betekenis hebben ze voor hem?

6. Op welke wijze is Bonhoeffers ethiek praktisch?

7. Leg de samenvatting van Bonhoeffers ethiek d.m.v. «bidden, goed te doen en alles van God te verwachten».





