project:
  type: book
  output-dir: docs

book:
  title: "christelijke_ethiek"
  author: "Berend Coster"
  date: "09/06/2025"
  chapters:
    - index.qmd
    - ethiekalswijsheid.qmd
    - volgendehoofdstuk.qmd
    
format:
  html:
    theme:
      - cosmo
      - brand


