project:
  type: book
  output-dir: docs

book:
  title: "Christelijke ethiek"
  author: "Berend Coster"
  date: "09/06/2025"
  chapters:
    - 0index.qmd
    - 01ethiekalswijsheid.qmd
    - 02ethischebegrippenenhetmoreleleven.qmd
    - 03watwealtijdmoetenverdedigen.qmd
    - 04demensiseenmoreelwezen.qmd
    - 05dewaardenvolgensdewet.qmd
    - 06dedecaloog.qmd
    - 07devrijheidvandewetendewetvandevrijheid.qmd
    - 08dewetblijftvankracht.qmd
    - 09dewaardenvolgenshetevangelie.qmd
    - 10devolmaaktheidvandediscipelen.qmd
    - 11deethiekvanhetkoninkrijk.qmd
    - 12wijsheidalsverantwoordelijkleven.qmd
    - 13dewijsheidspedagogiekvanspreuken.qmd
    - 14dewijsheidinpredikereninhetnt.qmd
    - 15deheiligegeestenhetgeweten.qmd
    - 16debijbelseenchristelijkewaarden.qmd
    - 17dedeugdenverinnerlijktewaarden.qmd
    - 18heiligingalsmoreleuitdaging.qmd
    - 19dewaardenethiekvancslewis.qmd
    - 20deethiekalsnavolgingbijdb.qmd
    
    
format:
  html:
    theme:
      - cosmos
      - assets/custom.css


