project:
  type: book
  output-dir: docs

book:
  title: "Christelijke ethiek"
  author: "Berend Coster"
  date: "09/06/2025"
  chapters:
    - index.qmd
    - ethiekalswijsheid.qmd
    - ethischebegrippenenhetmoreleleven.qmd
    - watwealtijdmoetenverdedigen.qmd
    - demensiseenmoreelwezen.qmd
    - dewaardenvolgensdewet.qmd
    - dedecaloog.qmd
    - devrijheidvandewetendewetvandevrijheid.qmd 

    
    
format:
  html:
    theme:
      - cosmos


