project:
  type: book
  output-dir: docs

book:
  title: "Christelijke ethiek"
  author: "Berend Coster"
  date: "09/06/2025"
  chapters:
    - 0index.qmd
    - 01ethiekalswijsheid.qmd
    - 02ethischebegrippenenhetmoreleleven.qmd
    - 03watwealtijdmoetenverdedigen.qmd
    - demensiseenmoreelwezen.qmd
    - dewaardenvolgensdewet.qmd
    - dedecaloog.qmd
    - devrijheidvandewetendewetvandevrijheid.qmd
    - dewetblijftvankracht.qmd
    - dewaardenvolgenshetevangelie.qmd
    - devolmaaktheidvandediscipelen.qmd
    - deethiekvanhetkoninkrijk
    - wijsheidalsverantwoordelijkleven.qmd
    - dewijsheidspedagogiekvanspreuken.qmd
    - dewijsheidinpredikereninhetnt.qmd
    - deheiligegeestenhetgeweten.qmd
    - debijbelseenchristelijkewaarden.qmd
    - dedeugdenverinnerlijktewaarden.qmd
    - heiligingalsmoreleuitdaging.qmd
    - dewaardenethiekvancslewis.qmd
    - deethiekalsnavolgingbijdb.qmd
    
    
format:
  html:
    theme:
      - cosmos
      - assets/custom.css


