# DE MENS IS EEN MOREEL WEZEN

*De Bijbelse ethiek is wijsheid, en wijsheid is goed weten te leven in de vreze des Heren, in de verhouding tot de anderen en tot onszelf. Deze ethiek beveelt een verantwoordelijk leven aan: gevoel te hebben en verantwoordelijkheid te nemen voor alles wat waarde heeft. We onderscheidden vitale en sociale waarden, waarden die groter zijn dan het eigen leven en tenslotte de pure waarden, de principes en kwaliteiten die het leven diepte en glans geven. Al deze waarden zijn deel van de goede schepping.*

## Dienen en bewaren 

Het boek Genesis geeft een speciale plaats aan de mens, geschapen in het beeld en naar de gelijkenis van God (Genesis 1.26,27). Hij is Gods rentmeester of misschien beter gezegd, Gods erfenaam. De aarde met de dieren- en plantenwereld worden aan hem onderworpen en aan hem aangepast door de namen die hij geeft (Genesis 2.19). Zijn opdracht is de Hof van Eden heeft te bewerken en te bewaren (Genesis 2.15)1. De mens hoeft dus de Hof niet te cultiveren, in cultuur te brengen, zoals sommige vertalingen zeggen, want God heeft hem geplant, maar moet hem dienen en zijn heelheid bewaren, dat is in zijn waarde laten. Het leven in de Hof is in alle opzichten een leven in goede werken, die God voorbereid heeft om daarin te wandelen (Ef. 2.10). Het eten van alle bomen, met name van de Boom des Levens, en het drinken van het water van de vier rivieren die uit eenzelfde bron ontspringen, symboliseren het goede leven. De Boom van Kennis van Goed en Kwaad geeft de grens aan. Achter deze grens ligt alles wat God niet voor de mens heeft bedoeld: de dood, het verlies van het leven en de terugkeer tot het stof, het viervoudige niets van het begin (Genesis 1.2; 2.9-7).

## De mens schuldig aan en slachtoffer van de zonde

Genesis 2.25 benadrukt dat de mens naakt was, maar zich niet schaamde. Wel blijkt dat hij kwetsbaar is, als het kwaad in de vorm van een psychologisch weldoordachte leugen de goede schepping binnendringt. De slang verzwakt het Woord van God en vervangt het gebod niet te eten van de Boom van Kennis van Goed en Kwaad door een theologie van beneden, de mogelijkheid als God te zijn. De hoogste uitdaging van de mens is inderdaad volmaakt te zijn in heiligheid, zoals de Vader volmaakt is, echter de grootste verleiding is God te willen evenaren in kennis en macht (Lev. 11.44; Mattheüs 5.48). Het gelukt de slang de mens te verleiden met hetzelfde motief als dat zij gehad had om tegen God in opstand te komen. Ze zaait twijfel: (1) intellectuele twijfel aangaande de geldigheid van het gebod (Heeft God dit werkelijk gezegd?), (2) twijfel aangaande de morele geldigheid ervan (de suggestie dat het onmogelijk verkeerd is om te eten van een vrucht die zo aantrekkelijk is) en (3) twijfel aangaande de rechtvaardigheid van het gebod (de slang suggereert dat het slechts dient om Gods voorrechten te beschermen).

Het betoog van de slang is een absurde leugen, maar heeft catastrofale gevolgen. De relatie tussen man en vrouw wordt complex en er komt scheiding tussen God en mens. De zonde heeft intrede gedaan in de goede schepping, als leugen en ongehoorzaamheid. De mens heeft overmoedig en driest de vreze des Heren opzij gezet (zie psalm 36.1). Zonde is ook verlies lijden (Spreuken 8.36). Als we tegen een vriend zondigen, dan verliezen we zijn vriendschap. Als we tegen onze echtgenoot of echtgenote zondigen, verliezen we het huwelijk. Door tegen God te zondigen, verliest de mens de relatie met zijn Schepper. Adam en Eva zondigden en op hetzelfde moment werden ze van God gescheiden (Jes. 59.2). Door het bedrog van de slang waren ze slachtoffer van het kwaad, evenwel verantwoordelijk voor hun eigen daden.

### Het morele geweten van de mens

De scheiding van God betekende de dood, maar de Here had medelijden met Adam en Eva. Hij zocht hen op in hun schuilplaats, riep hen ter verantwoording en beloofde verlossing. De voorzienigheid trad in werking: Gods bewaring en onderhouding van de schepping, in toestand van zonde en met het oog op het herstel van alle dingen. Het interim van de algemene genade tussen de schepping en de voleinding, de tijd van de ethiek. De mensen werden weliswaar verdreven uit de Hof en zelfs werd de aarde vervloekt om hunnentwille, maar tegelijk werd hun een zekere bescherming geboden. God zette vijandschap tussen de mensheid en de boze, waardoor de verhouding met het kwaad altijd ongemakkelijk is (Genesis 3.14, 15). Het fascineert ons en we kunnen en willen het niet voorkomen, maar het veroorzaakt ook gevoelens van angst, schaamte en schuld. Bovendien hebben we een wet in ons hart, in ons geweten, die ons aan het goede herinnert (Rom. 2.14, 15).

### Verharding

Het gevaar is dat we ons verharden tegen onze natuurlijke vrees voor en afkeer van het kwaad. Dit gebeurt als we het goede minachten en bespotten, ons gewennen aan het kwaad en er ongevoelig voor worden, toegeven aan zijn duistere en verleidende kracht en de vrees voor de gevolgen verliezen. Uiteindelijk voelen we dan geen schuld of schaamte meer. Tegelijk werkt het oordeel van God in dit proces, als hij ongehoorzaamheid straft met nog meer ongehoorzaamheid, zonde met nog meer zonde en morele onreinheid met nog meer onreinheid (zie de Egyptische plagen Exodus 1ss.; Psalm 81.12; Dan.12.10; Op. 22.11). Daarbij heeft elke tijd zijn eigen vormen van verharding en ongevoeligheid voor het kwaad. Historische en hedendaagse voorbeelden van wreedheid, onderdrukking en vernedering waarschuwen ons, maar onze samenleving is vooral ongevoelig voor relativisme, morele onverschilligheid, overdaad en wellust.

### Slot

Wij bevestigen dat de mens een moreel wezen is. Hij kent het goede door het verloren beeld en de verloren gelijkenis van God en het kwade door de zonde in eigen en andermans leven, maar deze kennis is niet bij machte ons te leiden. Ons wezen moet veranderd en vernieuwd worden door de wedergeboorte en we hebben nauwkeurigere instructies nodig aangaande goed en kwaad, welke we ontvangen door het Woord van God, in de vorm van wet, evangelie en wijsheid.

### Uitweiding: rentmeester of erfgenaam?

¿Hoe begrijpen we de relatie van de mens met de schepping? Het traditionele begrip voor deze relatie is rentmeesterschap. «Zoals een rentmeester zorg draagt voor het land van zijn heer, zo heeft de mens de taak om Gods schepping zorgvuldig te beheren». Prof. dr. Gijsbert v.d. Brink heeft recent de bezwaren bij dit begrip genoemd en het gebruik ervan bepaald2. Deze bezwaren zijn dat de mens teveel in het middelpunt van en boven de schepping geplaatst wordt, terwijl hij er ook deel van is. Door het begrip rentmeesterschap krijgt verantwoordelijkheid een administratief en instrumenteeel karakter. De schepping verliest haar eigen waarde; ze mag worden gecultiveerd, geëxploiteerd en rendabel gemaakt worden.

Van de Brink stelt voor begrip rentmeesterschap niet af te schaffen, maar aan te vullen met «beelden die sterker de eenheid en onderlinge afhankelijkheid uitdrukken van mens en natuur (of preciezer gezegd: van de mens en de niet-menselijke natuur, want we maken zelf ook deel uit van de natuur)». Ik stel voor als antwoord op de suggestie van Vd. Brink te overwegen het begrip erfenis of erfdeel. Het is een veelzijdig Bijbels begrip, met eigen woorden in het Hebreeuws en het Grieks3. De landbelofte is deel van het verbond van God met Israël, dat het recht van Israël op het beloofde land, in de termen van erfrecht beschrijft (Genesis 15.18;Nu. 32.32). Hetzelfde woordgebruik zien we terug bij de verdeling van het land en het vaststellen van het stamgebied van de verschillende stammen (Nu.18.20) en bij het particuliere recht van iedere Israëliet op zijn deel van het land (Joz. 24.32; 1K. 21). Ook wordt het in omgekeerde zin gebruikt: Israël is Gods erfenis/erfdeel, evenals het land (Ex.15.17; 34.9; Psalm 16.5). Evenwel hebben ook de volken hun nationale grondgebied als een erfenis van God ontvangen, zodat alles wat geldt voor Israël bij wijze van analogie ook geldt voor de volken (Deuteronomium 32.8). Het erfelijk en nationale recht op het land/de aarde wordt zowel in het Oude als het Nieuwe Testament tot een geestelijk recht: wie de Here verwachten, de rechtvaardigen en de zachtmoedigen, zullen de aarde beërven (Psalm 37.9, 29; Jesaja 60.21; Mattheüs 5.5; Romeinen 4.13). Het erfdeel moet bewaard worden voor de volgende generaties (Ruth 4.5), kan dus verloren gaan, verworpen worden en vervreemd (Jer.12.7,8; Kl.5.2). In het Nederlands gebruiken we een woord dat verwant is met erf: grond behorend bij een boerderij, een hoeve, een hofstede. Erfenis, erfdeel is dus voorvaderlijk (grond)bezit, waarvoor ieder generatie verantwoordelijk is. Samenvattend: het Bijbelse begrip voor eigendom is erfenis, erfdeel, erfelijk bezit. Het verenigt iedere Israëliet, met zijn volk, zijn land en zijn God in één lotsbestemming. Het is steeds een combinatie van geestelijk, moreel en materieel recht, met de bijbehorende verplichtingen.

### Oefeningen

1.  Definieer opnieuw de christelijke ethiek.

2.  Leg de scheppingsopdracht van Genesis 2.15 uit.

3.  Leg Ef.2.15 uit in verband met de scheppingsopdracht.

4.  Leg het dienen en bewaren uit als een morele opdracht.

5.  Leg uit waarvoor de Boom van Kennis van Goed en Kwaad in morele zin symbool staat.

6.  Waarom is de mens zowel schuldig aan als slachtoffer van de zonde?

7.  Wat betekent de naaktheid van de mens in morele zin?

8.  Waarom is het aan God gelijk zijn tegelijk de hoogste uitdaging en de grootste verleiding voor de mens?

9.  Beschrijf de psychologische kracht van de leugen van de slang.

10. Definieer de zonde door middel van Psalm 36.1 en Spreuken 8.36 (te lezen in verschillende vertalingen).

11. Definieer de voorzienigheid en de algemene genade.

12. Wat is de relatie tussen de ethiek en de voorzienigheid?

13. Hoe uit zich de vijandschap tussen de mens en de boze in het geweten van de mens?

14. Welke is de dubbelzinnige verhouding van de mens met het kwaad?

15. Hoe voltrekt zich de verharding?

16. Leg uit hoe God actief is in de verharding door zijn oordeel.

17. Leg uit dat de mens een zwak moreel wezen is.

18. Wat zijn de bezwaren tegen het begrip rentmeesterschap?

19. Is het wenselijk en mogelijk het begrip erfenis en erfdeel weer terug te brengen in de ethiek?
