# De wet blijft van kracht  
*De wet, de openbaring van Gods heilige wil, bevestigt en onthult de voor alle tijden geldende waarden. Evenwel, haar effecten voor het morele leven zijn paradoxaal vanwege onze morele condities. De wet wil ons leven hoog en zuiver voor ons bewaren, maar vernedert ons en veroordeelt ons vanwege onze zonden. Het evangelie daarentegen spreekt ons vrij van de veroordeling, vanwege de verdienste van Christus, door het geloof. Vervolgens leert het ons dezelfde wet, die nu een wet van vrijheid is, vrijwillig te gehoorzamen. Op deze wijze blijft de wet van kracht.*
	
## De wet is realistisch

De Bijbelse de wet is niet idealistisch en ook niet ascetisch, maar verwijst naar God en eert Hem als hoogste wetgever.  Afgoderij maakt altijd de schepping goddelijk, de zon, de maan, de aarde, de zee, enz., maar de Bijbelse ethiek bevestigt haar karakter als geschapen werkelijkheid. In zekere zin wordt al het bestaande door de scheppingsgedachte geseculariseerd en teruggebracht tot de menselijke maat. De heidense culturen verheerlijkten de mannen – de helden en de vrije mannen – en vernederden de slaven, de onvrijen en de vrouwen. De Bijbelse ethiek daarentegen humaniseert en personaliseert alle mensen door ze te zien als gelijkwaardigen, geschapen in het beeld en naar de gelijkenis van God en door allen bescherming te bieden door de wet. Aan het einde van het Oude Testament is de vrouw niet langer eigendom van haar man, maar zijn metgezellin, de vrouw van zijn verbond (Mal.2.14). De slavernij van een Israëliet duurde niet levenslang, maar ‘slechts’ zeven jaar (Lev. 25). Bovendien had elke slaaf, ook als hij uit een ander volk stamde, één vrije dag in week. De sabbat was een recht dat voor ieder gold (Deut. 5.14). We zagen al dat de sabbatswetten (de wekelijkse sabbat en het sabbats- en het jubeljaar) het instituut van de slavernij ondermijnden. 

## De Bijbel en de natuurwet

Hoewel de natuurwet – de studie en definitie van wat op zichzelf goed en rechtvaardig is – geen onderwerp is van de bijzondere openbaring, respecteert, bevestigt en specificeert de Bijbel, zowel het Oude als het Nieuwe Testament, de positieve inhoud ervan1. Zelfs is de Bijbel één van de belangrijkste bronnen van de natuurwet vanwege het scheppingsconcept, waardoor de mens niet alleen lichamelijk een schepsel van God is, maar ook in morele zin. Al onze waarden vinden hun oorsprong en liggen vast in de schepping. 

Uitgaande van de eenheid van de Thora en de natuurwet, kan de apostel Paulus zeggen dat allen die zondigen zonder de wet (van Mozes) ook verloren zullen gaan zonder die wet; en allen die zondigen, onder de wet van God, zullen door deze wet geoordeeld worden (Rom. 2.12), omdat mensen die de geopenbaarde wet niet kennen, deze wel in hun hart hebben (Rom. 2.14,15; zie 1.19,20; 2.27 ). We kunnen in de Bijbel zelfs elementen vinden die lijken op het Griekse denken over de natuurwet. In Rom. 1.26 verdedigt Paulus een natuurlijke seksualiteit, in Rom. 2.14 gaat hij uit van de natuurlijke kennis van goed en kwaad en in 1Cor.11.14 verdedigt hij een natuurlijke esthetiek. Het lijkt dat het woord geweten, dat we tegen komen in de theologie van Paulus en van  Petrus en ook in de brief aan de Hebreeën, maar dat afwezig is in het Oude Testament (LXX), zijn oorsprong vindt in het stoïsche begrip van het natuurrecht (Johannes 8:9; Handelingen 23:1; 24.16; Rom. 2.15; 13.5; 1Cor.8.7,10,12; 10.25-29; 2Cor. 1.12; 4.2; 5.11; 1Tim.1.5,19; 4.2; 2Tim.3.9; 4.2; Titus 1.15; Hebr. 9,9, 14; 10,2, 22; 13,8; 1P.2.19; 3,16,21).

## De scheppingsordeningen

Het natuurrecht en de basiswaarden van de ethiek worden zichtbaar in de zogenaamde scheppingsordeningen2. Theoretisch moeten we onderscheid maken tussen de ordeningen die deel uitmaken van Gods oorspronkelijke schepping en andere die hun oorsprong hebben in de voorzienigheid, maar in de praktijk is het moeilijk dit onderscheid te handhaven en daarom vatten we ze alle samen onder hetzelfde woord, scheppingsordeningen:
- Het  recht van de schepping, het dienen en bewaren van de schepping (Genesis 2.15).
- Het recht van het leven van mens, dier en plant (6e gebod; Gen. 9.4,6; Ex.23.19; 34.26; Deut.14.21; 20.19; 22.6; 25.4; Spr. 12.10; Handelingen.15.20,29; Rom.8.20 - 23; Ap.11.18).
 - Het recht van het huwelijk: het is niet goed voor een mens alleen te zijn (7e, 10e gebod; Gen. 2.18).
 - Het recht van voortplanting en gezin: de mens wordt geboren, groeit op en wordt opgevoed in een gezin (Genesis 1.28; 9.7; 5e gebod; Spr. 1-9).
- Het recht van arbeid en loon, ook de verplichting tot arbeid (Genesis 2.15; 4e gebod; 2Th. 3.10-12; Jak.5.1-6).
- Het recht van eigendom en vooral erfenis: land, huis, kleding, voedsel, productiemiddelen, enz. (6e, 10e gebod; Deuteronomium; 1Kon.21; ).
- Het recht van de staat (wettelijk georganiseerde samenleving): de mens leeft in collectieve gemeenschappen die worden vertegenwoordigd en geregeerd door een hoofd: staatshoofd of koning (Deut. 17.14-20; Rom.13; 1P.2.17). 
- Het recht van de economie, de exploitatie van de productiemiddelen en de consumptie is nooit een volledig individueel recht, noch een volkomen collectief recht (Deut.20.19; 2Thes.3.10).
- Het recht van een eerlijke en rechtvaardige rechtspraak, gerechtigheid in het oordeel (9e gebod; Deut. 16.20; Miq.6.6-8; Matteüs 5.17-20; Jak. 4.11-12). 
- Het recht van rust (Genesis 2.2; 4e gebod; Marcus 2.27).
- Het recht van God, Zijn exclusieve en heilige Naam en de openbaring van Zijn Raad (1,2,3e gebod; 1P.2.17).

## De crisis van het natuurrecht en de scheppingsordeningen

Vanaf de XVIII eeuw heeft de christelijke ethiek meer en meer afstand genomen van het natuurrecht en van de scheppingsordeningen door twee elkaar aanvullende bewegingen:

1. De nadruk op het natuurrecht en de natuurwet in de Verlichting, waardoor de Bijbelse openbaring werd achtergesteld bij het natuurrecht. De gedachte dat de mens op grond van de natuurwet zich voldoende ethisch kan oriënteren. Bij Rousseau staat de primitieve natuurmens op hoger ethisch niveau dan de z.g. cultuurmens. Emmanuel Kant dwingt de mens tot ethische autonomie, oriëntatie op zijn eigen aangeboren – rationeel – ethisch kompas. In het denken van de Verlichting behield de Bijbelse openbaring slechts gezag in zoverre zij het autonome denken zou kunnen respecteren en bevorderen. 

2. Ook verloor het natuurrecht terrein door de grote revolutionaire ontsporingen. De nadruk op natuurlijke vrijheid en gelijkheid maakte de Franse Revolutie, die begon als politieke omwenteling, tot een morele revolutie. De Russische revolutie brak met het geldende waardesysteem door de gelijkheid alle prioriteit te geven. De Duitse revolutie verhief ras en volk tot de hoogste ethische principe. Door het verheffen van deze verschillende natuurlijke condities – bepaalde en eenzijdige vitale, sociale en grote waarden – geraakte de leer van het natuurrecht en de scheppingsordeningen in diskrediet. 

Het ideologische misbruik het natuurrecht versterkte in de tweede helft van de XX  het ethische relativisme. Nadat de Bijbel had afgedaan als gezaghebbende stem, verloor ook de oriëntatie op het natuurrecht zijn gezag. Dit versterkte de gedachte van de autonome mens, die zelf zijn identiteit bepaalt en zelf zijn waardepatroon samenstelt. Abraham Kuyper probeerde deze tendens te corrigeren door het natuurrecht een hoge plaats te geven in zijn leer van de gemene gratie of algemene genade, maar twee andere belangrijke theologen van de XX eeuw spraken hun twijfel uit over de geldigheid ervan: Karl Barth vanwege zijn christocentrische theologie en Dietrich Bonhoeffer vooral vanwege het misbruik van het idee van de scheppingsorde in het racisme van het nationaalsocialisme. 

## Drievoudige toepassing

De gereformeerde theologie heeft de relevantie van de oudtestamentische wet voor het geestelijke leven en voor de ethiek begrepen door onderscheid te maken tussen drie verschillende toepassingen:  

1. De pedagogische toepassing, die de functie van de wet in de orde van het heil aangeeft: de wet overtuigt van zonde (Romeinen 3. 20; 5. 20; 5.13; 7. 7,8,9,11; Galaten 2.19; 3.24; 3.21).

2. De didactische toepassing: de Oudtestamentische wet geldt in het leven van de christen als een wet van vrijheid, een levensregel die Gods wil t.a.v. het morele leven samenvat en waaraan de gelovige zich vrijwillig onderwerpt. Heiliging gebeurt volgens haar principes (Rom. 3.31; 1Kor. 9.21; Jak.1.25; 2.8-12; Johannes 14.15, 21; 15.10; 1 Johannes 2.3-5).

3. De burgerlijke en morele toepassing; het gezag van de Bijbelse wet, in overeenstemming met het natuurrecht, in de sfeer van de voorzienigheid en de algemene genade, in de samenleving, de cultuur, de politiek en de economie. Zelfs culturen die geen kennis hebben van de geopenbaarde wet, herkennen haar door het geweten (Rom. 1.19,20; 2.12, 14,15, 27). De culturen worden gehumaniseerd als ze de universele morele wetten en het mensenrecht erkennen als Gods wet. 

## De wet blijft van kracht
	
De Bijbelse wet schrijft geen politiek of sociaal-economisch model voor alle tijden voor, maar spreekt het volk van God aan als dienaren die Zijn wil behoren te doen. Haar waarden vertegenwoordigen hoogstaande menselijke houdingen, motieven en deugden. Zij is flexibel ten opzichte van historische omstandigheden die kunnen veranderen, maar roept te allen tijde op tot de erkenning en waardering van haar waarden, het naleven van haar normen, het respecteren van haar motieven en het ontwikkelen van haar deugden. Zo heeft de Here Jezus haar begrepen toen hij haar met al haar implicaties samenvatte in het krachtige dubbele gebod de Here onze God, lief te hebben met heel ons hart, met heel onze ziel en met heel ons verstand, en onze naaste als als onszelf. (Mattheüs 5.17-19; 22.37-39).

## Oefeningen

1. Wat betekent het dat de wet van het Oude Testament niet idealistisch is en niet ascetisch?

2. Op welke wijze seculariseert de wet de schepping?

3. Op welke wijze heeft de wet een humaniserende en personaliserende kracht?

4. Hoe verhouden Bijbel en natuurwet zich tot elkaar?

5. Leg uit de betekenis van Rom.2.14 en 1Cor. 11.14.

6. Leg uit welke christelijke inhoud gegeven wordt in het Nieuwe Testament aan het geweten?

7. Leg uit het begrip scheppingsordeningen.

8. Welke zijn de belangrijkste scheppingsordeningen?

9. Verklaar de crisis van het natuurrecht.

10. Onderzoek en bespreek de verschillende waardering van het natuurrecht en de scheppingsordeningen bij Abraham Kuyper, Karl Barth en Dietrich Bonhoeffer.

11. Welke zijn de drie toepassingen van de wet in een christelijke samenleving?
    
12. Op welke wijze is flexibiliteit de kracht van de Bijbelse wet?