# ETHIEK ALS WIJSHEID {#sec-wijsheid}

*Het onderwerp van de ethiek of de moraaltheologie is het goede leven. Hoe kunnen we goed leven en goed leren leven? Dit verlangen naar goed leven in morele zin, is wat de Bijbel verstaat onder wijsheid. Hoewel wijsheid ook intelligentie, scherpzinnigheid en bekwaamheid is, is ze altijd en vooral weten hoe je goed moet leven in morele en geestelijke zin. De man of vrouw die goed weet te leven in zijn of haar relatie met God, met zijn of haar naaste en met zichzelf, is wijs. De belangrijkste voorwaarde ervoor is de vreze des Heren, want het begin van wijsheid – van het goede leven – is de vreze des Heren (Spr. 9.10; 1.7; Psalm 11.10).*

## De vreze des Heren

Het woord vreze des Heren heeft altijd de suggestie van respect en eerbied in zich, zelfs van schrik en angst vanwege de grootheid en majesteit van de Here, die vreeswekkend en angstaanjagend is (Psalm 47.2; 76.11; Jesaja 6.5; Jeremia 20.11). De betekenis van het woord is echter wat het Nieuwe Testament uitdrukt door de drie basiswoorden die onze relatie met God beschrijven: geloof, hoop en liefde. Dus: het begin, het principe, de meest fundamentele voorwaarde voor een goed leven, is de Here te vrezen, de God van Israël, de Vader van Jezus Christus. In Hem te geloven, op Hem te hopen en Hem lief te hebben in geloof, gehoorzaamheid en verantwoordelijkheid.

## Het doel en effect van ethiek

De christelijke ethiek, het geheel van de morele voorwaarden van goed leven voor de discipelen van de Here Jezus, staat in verband met de dankbaarheid voor de verlossing die ons het evangelie belooft. Het is het verlangen om goed te leven – moreel en geestelijk – met het oog op de eer van God, het welzijn van anderen en ook onze persoonlijke vrede en welstand, door een goed en gerust geweten. Ethiek, op deze manier begrepen, is de vrucht van de verlossing, die tot uiting komt in geestelijke en morele deugden, zelfs de vernieuwing van ons karakter (zie [Gal.5.22](https://herzienestatenvertaling.nl/teksten/galaten/5#6)). Dit geruste geweten is onbekend bij de goddelozen, dat zijn degenen die God niet vrezen (Psalm 36.1; Jes. 48.22; 57.21; Psalm 1). Hun leven leven toont de gevolgen van het immorele leven dat in de Bijbel vlees wordt genoemd (Gal.5.19).

## Wet, wijsheid en evangelie

Het is voor niemand eenvoudig om goed te leven in de vreze des Heren, omdat ons bestaan tussen twee tegengestelde polen ligt. Aan de ene kant de wet van God die ons veroordeelt en aan de andere kant het evangelie van Zijn genade, dat ons zijn barmhartigheid en vergeving biedt. Dat wil zeggen: hoe kunnen we goed leven, terwijl enerzijds de geboden van God ons veroordelen vanwege onze zonden (afgoderij, onreinheid, hardheid en leugen) en anderzijds de genade ons volledige vergeving van al onze zonden belooft? Kunnen we de zonde volledig vermijden – wat de wet van ons eist – of kunnen we zo vertrouwen op Gods genade en vergeving dat we ons op geen enkele manier zorgen hoeven te maken over onze zonden? Het antwoord is wat we al gaven: we moeten een manier van leven zoeken die rekening houdt met zowel de wet als de genade. Als we de heilige wet van God negeren, geven we ons over aan losbandigheid en wanorde. Als we het evangelie van Gods genade vergeten, geraken we tot wetticisme, dat altijd het geweten belast. Het is de wijsheid die ook van God komt, die een ruimte voor ons schept tussen de wet en de genade. waarin het ons toegestaan wordt een verantwoordelijk en een gerust leven te leiden.

## Tegelijkertijd rechtvaardig en zondig

De tegenstelling tussen de wet en de genade, die fundamenteel is voor het begrip van ethiek, toont zich in ons leven als een dubbele geestelijke werkelijkheid. Vanwege de zonde zijn we beklagenswaardige en schuldige mensen, omdat de zonde niet alleen verwijst naar het kwaad dat we doen, maar ook naar het kwaad dat we zijn. Wij zijn zondaars omdat het kwaad dat we doen ons definieert als de oorsprong en oorzaak ervan. Wijzelf zijn de oorsprong van onze leugens, van onze hardheid en ongevoeligheid en van onze morele onzuiverheid. Aan de andere kant zijn wij, als mensen die wedergeboren zijn door de liefde van God, door de genade van Jezus Christus en door het werk van de Heilige Geest, heilig en rechtvaardig. We zagen al dat de morele deugden die we door deze genade kunnen hebben, inclusief de verbetering van ons karakter, in het evangelie de vrucht van de Heilige Geest worden genoemd (Gal. 5.22).

## Slot

We gaven in dit eerste hoofdstuk van Waarden en Verantwoordelijkheid een definitie van de Bijbelse ethiek d.m.v. het begrip wijsheid. Ethiek in Bijbelse zin is wijsheid en wijsheid is goed weten te leven in de vreze des Heren. Het goede leven is zowel vrij als verantwoordelijk, in een ruimte waar de wet en en de genade elkaar ontmoeten en waar we tegelijkertijd zondaars en toch rechtvaardigen zijn.

Illustratie 1; Wet, wijsheid, evangelie

## Oefeningen

1.  Wat is wijsheid in Bijbelse zin?

2.  Wie is de wijze van Mattheüs 7.24-27?

3.  Wat is de relatie tussen de verlossingsleer en de ethiek?

4.  Waarom is de christelijke ethiek zo complex?
