---
editor: 
  markdown: 
    wrap: 72
---

# INLEIDING

Het lesmateriaal voor de cursus Theologische Vorming Gemeenteleden onder
de titel Waarden en Verantwoordelijkheid bestaat uit een reeks van ¿27?
beknopte hoofdstukken, oorspronkelijk in het Spaans geschreven en
gepubliceerd in het Spaanstalige blad van de Stichting In de Rechte
Straat (En la Calle Recta), in de jaren 2018 tot 2023. De artikelen zijn
een samenvatting van het lesmateriaal voor het vak Christelijke Ethiek,
gegeven op de Facultad Internacional de Teología, IBSTE, Castelldefels,
Spanje, in de jaren 2019-2024.

Inleiding

1\. Ethiek als wijsheid

2\. Ethische begrippen en het morele leven

3\. Wat we altijd moeten verdedigen

4\. De mens is een moreel wezen

5\. De waarden volgens de wet

6\. De Decaloog

7\. De vrijheid van de wet en de wet der vrijheid

8\. De wet blijft van kracht.

9\. De waarden volgens het evangelie

10\. De volmaaktheid van de discipelen

11\. De relevantie van de ethiek van het Koninkrijk

12\. Wijsheid als verantwoordelijk leven

13\. De wijsheidspedagogiek van Spreuken

14\. De wijsheid in Prediker en in het Nieuwe Testament

15\. De Heilige Geest en het geweten

16\. De Bijbelse en christelijke waarden

17\. Deugden, verinnerlijkte waarden

18\. Heiliging als morele uitdaging 19.

De waardenethiek van C.S. Lewis

20\. Ethiek als navolging van Christus, Dietrich Bonhoeffer

21\. Toegepaste ethiek 1: Leven en dood; geboorte en levenseinde (in
bewerking).

22\. Toegepaste ethiek 2: Huwelijk, gezin en seksualiteit (in
bewerking).

23\. Toegepaste ethiek 3: Rijkdom en Armoede (in bewerking).

24\. Toegepaste ethiek 4: Macht en politiek (in bewerking).

25\. Toegepaste ethiek 5; Oorlog en Vrede: (in bewerking).

26\. Toegepaste ethiek 6: De zorg voor de schepping (in bewerking).

27\. Eschatologisch perspectief
